"use strict";
/**
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.dev/license
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ɵrestoreComponentResolutionQueue = exports.ɵresolveComponentResources = exports.ɵisComponentDefPendingResolution = exports.ɵclearResolutionOfComponentResourcesQueue = exports.ɵComponentFactory = exports.ɵDEFAULT_LOCALE_ID = exports.ɵunregisterLocaleData = exports.ɵregisterLocaleData = exports.ɵLocaleDataIndex = exports.ɵgetLocalePluralCase = exports.ɵgetLocaleCurrencyCode = exports.ɵfindLocaleData = exports.ɵSSR_CONTENT_INTEGRITY_MARKER = exports.ɵreadHydrationInfo = exports.ɵIS_INCREMENTAL_HYDRATION_ENABLED = exports.ɵIS_HYDRATION_DOM_REUSE_ENABLED = exports.ɵJSACTION_EVENT_CONTRACT = exports.ɵwithEventReplay = exports.ɵwithIncrementalHydration = exports.ɵwithI18nSupport = exports.ɵwithDomHydration = exports.ɵannotateForHydration = exports.ɵRuntimeError = exports.ɵformatRuntimeError = exports.ɵXSS_SECURITY_URL = exports.ɵINJECTOR_SCOPE = exports.ɵisEnvironmentProviders = exports.ɵgetInjectableDef = exports.ɵsetCurrentInjector = exports.ɵconvertToBitFlags = exports.ɵDeferBlockState = exports.ɵDeferBlockBehavior = exports.ɵtriggerResourceLoading = exports.ɵrenderDeferBlockState = exports.ɵgetDeferBlocks = exports.ɵConsole = exports.ɵZONELESS_ENABLED = exports.ɵChangeDetectionScheduler = exports.ɵChangeDetectionSchedulerImpl = exports.ɵPROVIDED_NG_ZONE = exports.ɵinternalProvideZoneChangeDetection = exports.ɵdefaultKeyValueDiffers = exports.ɵdefaultIterableDiffers = exports.ɵinternalCreateApplication = exports.ɵTracingService = exports.ɵTracingAction = exports.ɵIMAGE_CONFIG_DEFAULTS = exports.ɵIMAGE_CONFIG = exports.ɵINTERNAL_APPLICATION_ERROR_HANDLER = exports.ɵsetAlternateWeakRefImpl = void 0;
exports.ɵgetClosestComponentName = exports.ɵResourceImpl = exports.ɵdisableProfiling = exports.ɵenableProfiling = exports.ɵPERFORMANCE_MARK_PREFIX = exports.ɵstopMeasuring = exports.ɵstartMeasuring = exports.ɵNOT_FOUND_CHECK_ONLY_ELEMENT_INJECTOR = exports.ɵtruncateMiddle = exports.ɵstringify = exports.ɵperformanceMarkFeature = exports.ɵisSubscribable = exports.ɵisPromise = exports.ɵglobal = exports.ɵdevModeEqual = exports.numberAttribute = exports.booleanAttribute = exports.ɵTESTABILITY_GETTER = exports.ɵTESTABILITY = exports.ɵ_sanitizeUrl = exports.ɵ_sanitizeHtml = exports.ɵunwrapSafeValue = exports.ɵgetSanitizationBypassType = exports.ɵallowSanitizationBypassAndThrow = exports.ɵsetInjectorProfilerContext = exports.ɵReflectionCapabilities = exports.ɵENABLE_ROOT_COMPONENT_BOOTSTRAP = exports.ɵALLOW_MULTIPLE_PLATFORMS = exports.ɵPendingTasksInternal = void 0;
var signals_1 = require("../primitives/signals");
Object.defineProperty(exports, "\u0275setAlternateWeakRefImpl", { enumerable: true, get: function () { return signals_1.setAlternateWeakRefImpl; } });
var error_handler_1 = require("./error_handler");
Object.defineProperty(exports, "\u0275INTERNAL_APPLICATION_ERROR_HANDLER", { enumerable: true, get: function () { return error_handler_1.INTERNAL_APPLICATION_ERROR_HANDLER; } });
var application_tokens_1 = require("./application/application_tokens");
Object.defineProperty(exports, "\u0275IMAGE_CONFIG", { enumerable: true, get: function () { return application_tokens_1.IMAGE_CONFIG; } });
Object.defineProperty(exports, "\u0275IMAGE_CONFIG_DEFAULTS", { enumerable: true, get: function () { return application_tokens_1.IMAGE_CONFIG_DEFAULTS; } });
var tracing_1 = require("./application/tracing");
Object.defineProperty(exports, "\u0275TracingAction", { enumerable: true, get: function () { return tracing_1.TracingAction; } });
Object.defineProperty(exports, "\u0275TracingService", { enumerable: true, get: function () { return tracing_1.TracingService; } });
var create_application_1 = require("./application/create_application");
Object.defineProperty(exports, "\u0275internalCreateApplication", { enumerable: true, get: function () { return create_application_1.internalCreateApplication; } });
var change_detection_1 = require("./change_detection/change_detection");
Object.defineProperty(exports, "\u0275defaultIterableDiffers", { enumerable: true, get: function () { return change_detection_1.defaultIterableDiffers; } });
Object.defineProperty(exports, "\u0275defaultKeyValueDiffers", { enumerable: true, get: function () { return change_detection_1.defaultKeyValueDiffers; } });
var ng_zone_scheduling_1 = require("./change_detection/scheduling/ng_zone_scheduling");
Object.defineProperty(exports, "\u0275internalProvideZoneChangeDetection", { enumerable: true, get: function () { return ng_zone_scheduling_1.internalProvideZoneChangeDetection; } });
Object.defineProperty(exports, "\u0275PROVIDED_NG_ZONE", { enumerable: true, get: function () { return ng_zone_scheduling_1.PROVIDED_NG_ZONE; } });
var zoneless_scheduling_impl_1 = require("./change_detection/scheduling/zoneless_scheduling_impl");
Object.defineProperty(exports, "\u0275ChangeDetectionSchedulerImpl", { enumerable: true, get: function () { return zoneless_scheduling_impl_1.ChangeDetectionSchedulerImpl; } });
var zoneless_scheduling_1 = require("./change_detection/scheduling/zoneless_scheduling");
Object.defineProperty(exports, "\u0275ChangeDetectionScheduler", { enumerable: true, get: function () { return zoneless_scheduling_1.ChangeDetectionScheduler; } });
Object.defineProperty(exports, "\u0275ZONELESS_ENABLED", { enumerable: true, get: function () { return zoneless_scheduling_1.ZONELESS_ENABLED; } });
var console_1 = require("./console");
Object.defineProperty(exports, "\u0275Console", { enumerable: true, get: function () { return console_1.Console; } });
var discovery_1 = require("./defer/discovery");
Object.defineProperty(exports, "\u0275getDeferBlocks", { enumerable: true, get: function () { return discovery_1.getDeferBlocks; } });
var rendering_1 = require("./defer/rendering");
Object.defineProperty(exports, "\u0275renderDeferBlockState", { enumerable: true, get: function () { return rendering_1.renderDeferBlockState; } });
var triggering_1 = require("./defer/triggering");
Object.defineProperty(exports, "\u0275triggerResourceLoading", { enumerable: true, get: function () { return triggering_1.triggerResourceLoading; } });
var interfaces_1 = require("./defer/interfaces");
Object.defineProperty(exports, "\u0275DeferBlockBehavior", { enumerable: true, get: function () { return interfaces_1.DeferBlockBehavior; } });
Object.defineProperty(exports, "\u0275DeferBlockState", { enumerable: true, get: function () { return interfaces_1.DeferBlockState; } });
var injector_compatibility_1 = require("./di/injector_compatibility");
Object.defineProperty(exports, "\u0275convertToBitFlags", { enumerable: true, get: function () { return injector_compatibility_1.convertToBitFlags; } });
Object.defineProperty(exports, "\u0275setCurrentInjector", { enumerable: true, get: function () { return injector_compatibility_1.setCurrentInjector; } });
var defs_1 = require("./di/interface/defs");
Object.defineProperty(exports, "\u0275getInjectableDef", { enumerable: true, get: function () { return defs_1.getInjectableDef; } });
var provider_1 = require("./di/interface/provider");
Object.defineProperty(exports, "\u0275isEnvironmentProviders", { enumerable: true, get: function () { return provider_1.isEnvironmentProviders; } });
var scope_1 = require("./di/scope");
Object.defineProperty(exports, "\u0275INJECTOR_SCOPE", { enumerable: true, get: function () { return scope_1.INJECTOR_SCOPE; } });
var error_details_base_url_1 = require("./error_details_base_url");
Object.defineProperty(exports, "\u0275XSS_SECURITY_URL", { enumerable: true, get: function () { return error_details_base_url_1.XSS_SECURITY_URL; } });
var errors_1 = require("./errors");
Object.defineProperty(exports, "\u0275formatRuntimeError", { enumerable: true, get: function () { return errors_1.formatRuntimeError; } });
Object.defineProperty(exports, "\u0275RuntimeError", { enumerable: true, get: function () { return errors_1.RuntimeError; } });
var annotate_1 = require("./hydration/annotate");
Object.defineProperty(exports, "\u0275annotateForHydration", { enumerable: true, get: function () { return annotate_1.annotateForHydration; } });
var api_1 = require("./hydration/api");
Object.defineProperty(exports, "\u0275withDomHydration", { enumerable: true, get: function () { return api_1.withDomHydration; } });
Object.defineProperty(exports, "\u0275withI18nSupport", { enumerable: true, get: function () { return api_1.withI18nSupport; } });
Object.defineProperty(exports, "\u0275withIncrementalHydration", { enumerable: true, get: function () { return api_1.withIncrementalHydration; } });
var event_replay_1 = require("./hydration/event_replay");
Object.defineProperty(exports, "\u0275withEventReplay", { enumerable: true, get: function () { return event_replay_1.withEventReplay; } });
var event_delegation_utils_1 = require("./event_delegation_utils");
Object.defineProperty(exports, "\u0275JSACTION_EVENT_CONTRACT", { enumerable: true, get: function () { return event_delegation_utils_1.JSACTION_EVENT_CONTRACT; } });
var tokens_1 = require("./hydration/tokens");
Object.defineProperty(exports, "\u0275IS_HYDRATION_DOM_REUSE_ENABLED", { enumerable: true, get: function () { return tokens_1.IS_HYDRATION_DOM_REUSE_ENABLED; } });
Object.defineProperty(exports, "\u0275IS_INCREMENTAL_HYDRATION_ENABLED", { enumerable: true, get: function () { return tokens_1.IS_INCREMENTAL_HYDRATION_ENABLED; } });
var utils_1 = require("./hydration/utils");
Object.defineProperty(exports, "\u0275readHydrationInfo", { enumerable: true, get: function () { return utils_1.readHydrationInfo; } });
Object.defineProperty(exports, "\u0275SSR_CONTENT_INTEGRITY_MARKER", { enumerable: true, get: function () { return utils_1.SSR_CONTENT_INTEGRITY_MARKER; } });
var locale_data_api_1 = require("./i18n/locale_data_api");
Object.defineProperty(exports, "\u0275findLocaleData", { enumerable: true, get: function () { return locale_data_api_1.findLocaleData; } });
Object.defineProperty(exports, "\u0275getLocaleCurrencyCode", { enumerable: true, get: function () { return locale_data_api_1.getLocaleCurrencyCode; } });
Object.defineProperty(exports, "\u0275getLocalePluralCase", { enumerable: true, get: function () { return locale_data_api_1.getLocalePluralCase; } });
Object.defineProperty(exports, "\u0275LocaleDataIndex", { enumerable: true, get: function () { return locale_data_api_1.LocaleDataIndex; } });
Object.defineProperty(exports, "\u0275registerLocaleData", { enumerable: true, get: function () { return locale_data_api_1.registerLocaleData; } });
Object.defineProperty(exports, "\u0275unregisterLocaleData", { enumerable: true, get: function () { return locale_data_api_1.unregisterAllLocaleData; } });
var localization_1 = require("./i18n/localization");
Object.defineProperty(exports, "\u0275DEFAULT_LOCALE_ID", { enumerable: true, get: function () { return localization_1.DEFAULT_LOCALE_ID; } });
var component_factory_1 = require("./linker/component_factory");
Object.defineProperty(exports, "\u0275ComponentFactory", { enumerable: true, get: function () { return component_factory_1.ComponentFactory; } });
var resource_loading_1 = require("./metadata/resource_loading");
Object.defineProperty(exports, "\u0275clearResolutionOfComponentResourcesQueue", { enumerable: true, get: function () { return resource_loading_1.clearResolutionOfComponentResourcesQueue; } });
Object.defineProperty(exports, "\u0275isComponentDefPendingResolution", { enumerable: true, get: function () { return resource_loading_1.isComponentDefPendingResolution; } });
Object.defineProperty(exports, "\u0275resolveComponentResources", { enumerable: true, get: function () { return resource_loading_1.resolveComponentResources; } });
Object.defineProperty(exports, "\u0275restoreComponentResolutionQueue", { enumerable: true, get: function () { return resource_loading_1.restoreComponentResolutionQueue; } });
var pending_tasks_1 = require("./pending_tasks");
Object.defineProperty(exports, "\u0275PendingTasksInternal", { enumerable: true, get: function () { return pending_tasks_1.PendingTasksInternal; } });
var platform_1 = require("./platform/platform");
Object.defineProperty(exports, "\u0275ALLOW_MULTIPLE_PLATFORMS", { enumerable: true, get: function () { return platform_1.ALLOW_MULTIPLE_PLATFORMS; } });
var bootstrap_1 = require("./platform/bootstrap");
Object.defineProperty(exports, "\u0275ENABLE_ROOT_COMPONENT_BOOTSTRAP", { enumerable: true, get: function () { return bootstrap_1.ENABLE_ROOT_COMPONENT_BOOTSTRAP; } });
var reflection_capabilities_1 = require("./reflection/reflection_capabilities");
Object.defineProperty(exports, "\u0275ReflectionCapabilities", { enumerable: true, get: function () { return reflection_capabilities_1.ReflectionCapabilities; } });
var injector_profiler_1 = require("./render3/debug/injector_profiler");
Object.defineProperty(exports, "\u0275setInjectorProfilerContext", { enumerable: true, get: function () { return injector_profiler_1.setInjectorProfilerContext; } });
var bypass_1 = require("./sanitization/bypass");
Object.defineProperty(exports, "\u0275allowSanitizationBypassAndThrow", { enumerable: true, get: function () { return bypass_1.allowSanitizationBypassAndThrow; } });
Object.defineProperty(exports, "\u0275getSanitizationBypassType", { enumerable: true, get: function () { return bypass_1.getSanitizationBypassType; } });
Object.defineProperty(exports, "\u0275unwrapSafeValue", { enumerable: true, get: function () { return bypass_1.unwrapSafeValue; } });
var html_sanitizer_1 = require("./sanitization/html_sanitizer");
Object.defineProperty(exports, "\u0275_sanitizeHtml", { enumerable: true, get: function () { return html_sanitizer_1._sanitizeHtml; } });
var url_sanitizer_1 = require("./sanitization/url_sanitizer");
Object.defineProperty(exports, "\u0275_sanitizeUrl", { enumerable: true, get: function () { return url_sanitizer_1._sanitizeUrl; } });
var testability_1 = require("./testability/testability");
Object.defineProperty(exports, "\u0275TESTABILITY", { enumerable: true, get: function () { return testability_1.TESTABILITY; } });
Object.defineProperty(exports, "\u0275TESTABILITY_GETTER", { enumerable: true, get: function () { return testability_1.TESTABILITY_GETTER; } });
var coercion_1 = require("./util/coercion");
Object.defineProperty(exports, "booleanAttribute", { enumerable: true, get: function () { return coercion_1.booleanAttribute; } });
Object.defineProperty(exports, "numberAttribute", { enumerable: true, get: function () { return coercion_1.numberAttribute; } });
var comparison_1 = require("./util/comparison");
Object.defineProperty(exports, "\u0275devModeEqual", { enumerable: true, get: function () { return comparison_1.devModeEqual; } });
var global_1 = require("./util/global");
Object.defineProperty(exports, "\u0275global", { enumerable: true, get: function () { return global_1.global; } });
var lang_1 = require("./util/lang");
Object.defineProperty(exports, "\u0275isPromise", { enumerable: true, get: function () { return lang_1.isPromise; } });
Object.defineProperty(exports, "\u0275isSubscribable", { enumerable: true, get: function () { return lang_1.isSubscribable; } });
var performance_1 = require("./util/performance");
Object.defineProperty(exports, "\u0275performanceMarkFeature", { enumerable: true, get: function () { return performance_1.performanceMarkFeature; } });
var stringify_1 = require("./util/stringify");
Object.defineProperty(exports, "\u0275stringify", { enumerable: true, get: function () { return stringify_1.stringify; } });
Object.defineProperty(exports, "\u0275truncateMiddle", { enumerable: true, get: function () { return stringify_1.truncateMiddle; } });
var provider_flags_1 = require("./view/provider_flags");
Object.defineProperty(exports, "\u0275NOT_FOUND_CHECK_ONLY_ELEMENT_INJECTOR", { enumerable: true, get: function () { return provider_flags_1.NOT_FOUND_CHECK_ONLY_ELEMENT_INJECTOR; } });
var profiler_1 = require("./profiler");
Object.defineProperty(exports, "\u0275startMeasuring", { enumerable: true, get: function () { return profiler_1.startMeasuring; } });
Object.defineProperty(exports, "\u0275stopMeasuring", { enumerable: true, get: function () { return profiler_1.stopMeasuring; } });
Object.defineProperty(exports, "\u0275PERFORMANCE_MARK_PREFIX", { enumerable: true, get: function () { return profiler_1.PERFORMANCE_MARK_PREFIX; } });
Object.defineProperty(exports, "\u0275enableProfiling", { enumerable: true, get: function () { return profiler_1.enableProfiling; } });
Object.defineProperty(exports, "\u0275disableProfiling", { enumerable: true, get: function () { return profiler_1.disableProfiling; } });
var resource_1 = require("./resource/resource");
Object.defineProperty(exports, "\u0275ResourceImpl", { enumerable: true, get: function () { return resource_1.ResourceImpl; } });
var get_closest_component_name_1 = require("./internal/get_closest_component_name");
Object.defineProperty(exports, "\u0275getClosestComponentName", { enumerable: true, get: function () { return get_closest_component_name_1.getClosestComponentName; } });
