"use strict";
/**
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.dev/license
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ɵɵclassMapInterpolate5 = exports.ɵɵclassMapInterpolate4 = exports.ɵɵclassMapInterpolate3 = exports.ɵɵclassMapInterpolate2 = exports.ɵɵclassMapInterpolate1 = exports.ɵɵclassMap = exports.ɵɵattributeInterpolateV = exports.ɵɵattributeInterpolate8 = exports.ɵɵattributeInterpolate7 = exports.ɵɵattributeInterpolate6 = exports.ɵɵattributeInterpolate5 = exports.ɵɵattributeInterpolate4 = exports.ɵɵattributeInterpolate3 = exports.ɵɵattributeInterpolate2 = exports.ɵɵattributeInterpolate1 = exports.ɵɵattribute = exports.ɵɵadvance = exports.ɵAcxViewEncapsulation = exports.ɵAcxChangeDetectionStrategy = exports.ɵFramework = exports.ɵDEFER_BLOCK_CONFIG = exports.ɵDEFER_BLOCK_DEPENDENCY_INTERCEPTOR = exports.ɵstore = exports.ɵsetLocaleId = exports.ɵsetClassDebugInfo = exports.ɵsetClassMetadataAsync = exports.ɵsetClassMetadata = exports.ɵNO_CHANGE = exports.ɵRender3NgModuleRef = exports.ɵNgModuleFactory = exports.ɵgetHostElement = exports.ɵgetDirectives = exports.ɵRender3ComponentRef = exports.ɵRender3ComponentFactory = exports.ɵNG_PIPE_DEF = exports.ɵNG_MOD_DEF = exports.ɵNG_ELEMENT_ID = exports.ɵNG_DIR_DEF = exports.ɵNG_COMP_DEF = exports.ɵgetLContext = exports.ɵsetAllowDuplicateNgModuleIdsForTest = exports.ɵɵregisterNgModuleType = exports.ɵcreateInjector = exports.ɵisInjectable = exports.ɵNG_PROV_DEF = exports.ɵNG_INJ_DEF = exports.ɵgetDebugNode = exports.ɵinjectChangeDetectorRef = exports.ɵcompileNgModuleFactory = exports.ɵisBoundToModule = void 0;
exports.ɵɵpipeBind4 = exports.ɵɵpipeBind3 = exports.ɵɵpipeBind2 = exports.ɵɵpipeBind1 = exports.ɵɵpipe = exports.ɵɵNgOnChangesFeature = exports.ɵɵnextContext = exports.ɵɵnamespaceSVG = exports.ɵɵnamespaceMathML = exports.ɵɵnamespaceHTML = exports.ɵɵloadQuery = exports.ɵɵlistener = exports.ɵɵinvalidFactory = exports.ɵɵinjectAttribute = exports.ɵɵInheritDefinitionFeature = exports.ɵɵi18nStart = exports.ɵɵi18nPostprocess = exports.ɵɵi18nExp = exports.ɵɵi18nEnd = exports.ɵɵi18nAttributes = exports.ɵɵi18nApply = exports.ɵɵi18n = exports.ɵɵdomProperty = exports.ɵɵgetInheritedFactory = exports.ɵɵgetCurrentView = exports.ɵɵenableBindings = exports.ɵɵelementStart = exports.ɵɵelementEnd = exports.ɵɵelementContainerStart = exports.ɵɵelementContainerEnd = exports.ɵɵelementContainer = exports.ɵɵelement = exports.ɵɵdisableBindings = exports.ɵɵdirectiveInject = exports.ɵɵdefinePipe = exports.ɵɵdefineNgModule = exports.ɵɵdefineDirective = exports.ɵɵdefineComponent = exports.ɵɵCopyDefinitionFeature = exports.ɵɵcomponentInstance = exports.ɵɵcontentQuerySignal = exports.ɵɵcontentQuery = exports.ɵɵconditionalBranchCreate = exports.ɵɵconditionalCreate = exports.ɵɵconditional = exports.ɵɵclassProp = exports.ɵɵclassMapInterpolateV = exports.ɵɵclassMapInterpolate8 = exports.ɵɵclassMapInterpolate7 = exports.ɵɵclassMapInterpolate6 = void 0;
exports.ɵɵstyleMapInterpolate7 = exports.ɵɵstyleMapInterpolate6 = exports.ɵɵstyleMapInterpolate5 = exports.ɵɵstyleMapInterpolate4 = exports.ɵɵstyleMapInterpolate3 = exports.ɵɵstyleMapInterpolate2 = exports.ɵɵstyleMapInterpolate1 = exports.ɵɵstyleMap = exports.ɵɵExternalStylesFeature = exports.ɵɵgetComponentDepsFactory = exports.ɵɵsetNgModuleScope = exports.ɵɵsetComponentScope = exports.ɵɵrepeaterTrackByIndex = exports.ɵɵrepeaterTrackByIdentity = exports.ɵɵrepeaterCreate = exports.ɵɵrepeater = exports.ɵɵrestoreView = exports.ɵɵresolveWindow = exports.ɵɵresolveDocument = exports.ɵɵresolveBody = exports.ɵɵresetView = exports.ɵɵreference = exports.ɵɵqueryRefresh = exports.ɵɵqueryAdvance = exports.ɵɵpureFunctionV = exports.ɵɵpureFunction8 = exports.ɵɵpureFunction7 = exports.ɵɵpureFunction6 = exports.ɵɵpureFunction5 = exports.ɵɵpureFunction4 = exports.ɵɵpureFunction3 = exports.ɵɵpureFunction2 = exports.ɵɵpureFunction1 = exports.ɵɵpureFunction0 = exports.ɵɵHostDirectivesFeature = exports.ɵɵProvidersFeature = exports.ɵɵpropertyInterpolateV = exports.ɵɵpropertyInterpolate8 = exports.ɵɵpropertyInterpolate7 = exports.ɵɵpropertyInterpolate6 = exports.ɵɵpropertyInterpolate5 = exports.ɵɵpropertyInterpolate4 = exports.ɵɵpropertyInterpolate3 = exports.ɵɵpropertyInterpolate2 = exports.ɵɵpropertyInterpolate1 = exports.ɵɵpropertyInterpolate = exports.ɵɵproperty = exports.ɵɵprojectionDef = exports.ɵɵprojection = exports.ɵɵpipeBindV = void 0;
exports.ɵɵtextInterpolate8 = exports.ɵɵtextInterpolate7 = exports.ɵɵtextInterpolate6 = exports.ɵɵtextInterpolate5 = exports.ɵɵtextInterpolate4 = exports.ɵɵtextInterpolate3 = exports.ɵɵtextInterpolate2 = exports.ɵɵtextInterpolate1 = exports.ɵɵtextInterpolate = exports.ɵɵtext = exports.ɵɵdeferHydrateOnViewport = exports.ɵɵdeferHydrateOnInteraction = exports.ɵɵdeferHydrateOnHover = exports.ɵɵdeferHydrateOnTimer = exports.ɵɵdeferHydrateOnImmediate = exports.ɵɵdeferHydrateOnIdle = exports.ɵɵdeferHydrateNever = exports.ɵɵdeferHydrateWhen = exports.ɵɵdeferEnableTimerScheduling = exports.ɵɵdeferPrefetchOnViewport = exports.ɵɵdeferPrefetchOnInteraction = exports.ɵɵdeferPrefetchOnHover = exports.ɵɵdeferPrefetchOnTimer = exports.ɵɵdeferPrefetchOnImmediate = exports.ɵɵdeferPrefetchOnIdle = exports.ɵɵdeferPrefetchWhen = exports.ɵɵdeferOnViewport = exports.ɵɵdeferOnInteraction = exports.ɵɵdeferOnHover = exports.ɵɵdeferOnTimer = exports.ɵɵdeferOnImmediate = exports.ɵɵdeferOnIdle = exports.ɵɵdeferWhen = exports.ɵɵdefer = exports.ɵɵtemplateRefExtractor = exports.ɵɵtemplate = exports.ɵɵsyntheticHostProperty = exports.ɵɵsyntheticHostListener = exports.ɵɵstylePropInterpolateV = exports.ɵɵstylePropInterpolate8 = exports.ɵɵstylePropInterpolate7 = exports.ɵɵstylePropInterpolate6 = exports.ɵɵstylePropInterpolate5 = exports.ɵɵstylePropInterpolate4 = exports.ɵɵstylePropInterpolate3 = exports.ɵɵstylePropInterpolate2 = exports.ɵɵstylePropInterpolate1 = exports.ɵɵstyleProp = exports.ɵɵstyleMapInterpolateV = exports.ɵɵstyleMapInterpolate8 = void 0;
exports.ɵɵsanitizeScript = exports.ɵɵsanitizeResourceUrl = exports.ɵɵsanitizeHtml = exports.ɵbypassSanitizationTrustUrl = exports.ɵbypassSanitizationTrustStyle = exports.ɵbypassSanitizationTrustScript = exports.ɵbypassSanitizationTrustResourceUrl = exports.ɵbypassSanitizationTrustHtml = exports.ɵmarkForRefresh = exports.ɵisViewDirty = exports.ɵViewRef = exports.ɵisNgModule = exports.ɵcompilePipe = exports.ɵɵngDeclarePipe = exports.ɵɵngDeclareNgModule = exports.ɵɵngDeclareInjector = exports.ɵɵngDeclareInjectable = exports.ɵɵngDeclareFactory = exports.ɵɵngDeclareDirective = exports.ɵɵngDeclareComponent = exports.ɵɵngDeclareClassMetadataAsync = exports.ɵɵngDeclareClassMetadata = exports.ɵɵFactoryTarget = exports.ɵtransitiveScopesFor = exports.ɵresetCompiledComponents = exports.ɵpatchComponentDefWithScope = exports.ɵflushModuleScopingQueueAsMuchAsPossible = exports.ɵcompileNgModuleDefs = exports.ɵcompileNgModule = exports.ɵresetJitOptions = exports.ɵcompileDirective = exports.ɵcompileComponent = exports.ɵsetDocument = exports.ɵLContext = exports.ɵCONTAINER_HEADER_OFFSET = exports.ɵɵattachSourceLocations = exports.ɵɵreplaceMetadata = exports.ɵɵreadContextLet = exports.ɵɵstoreLet = exports.ɵɵdeclareLet = exports.ɵsetUnknownPropertyStrictMode = exports.ɵgetUnknownPropertyStrictMode = exports.ɵsetUnknownElementStrictMode = exports.ɵgetUnknownElementStrictMode = exports.ɵɵtwoWayListener = exports.ɵɵtwoWayBindingSet = exports.ɵɵtwoWayProperty = exports.ɵɵviewQuerySignal = exports.ɵɵviewQuery = exports.ɵɵtextInterpolateV = void 0;
exports.ɵgetAsyncClassMetadataFn = exports.ɵgenerateStandaloneInDeclarationsError = exports.ɵUSE_RUNTIME_DEPS_TRACKER_FOR_JIT = exports.ɵdepsTracker = exports.ɵAfterRenderManager = exports.ɵnoSideEffects = exports.ɵɵvalidateIframeAttribute = exports.ɵɵtrustConstantResourceUrl = exports.ɵɵtrustConstantHtml = exports.ɵɵsanitizeUrlOrResourceUrl = exports.ɵɵsanitizeUrl = exports.ɵɵsanitizeStyle = void 0;
// we reexport these symbols just so that they are retained during the dead code elimination
// performed by rollup while it's creating fesm files.
//
// no code actually imports these symbols from the @angular/core entry point
var application_ref_1 = require("./application/application_ref");
Object.defineProperty(exports, "\u0275isBoundToModule", { enumerable: true, get: function () { return application_ref_1.isBoundToModule; } });
var application_ngmodule_factory_compiler_1 = require("./application/application_ngmodule_factory_compiler");
Object.defineProperty(exports, "\u0275compileNgModuleFactory", { enumerable: true, get: function () { return application_ngmodule_factory_compiler_1.compileNgModuleFactory; } });
var change_detector_ref_1 = require("./change_detection/change_detector_ref");
Object.defineProperty(exports, "\u0275injectChangeDetectorRef", { enumerable: true, get: function () { return change_detector_ref_1.injectChangeDetectorRef; } });
var debug_node_1 = require("./debug/debug_node");
Object.defineProperty(exports, "\u0275getDebugNode", { enumerable: true, get: function () { return debug_node_1.getDebugNode; } });
var defs_1 = require("./di/interface/defs");
Object.defineProperty(exports, "\u0275NG_INJ_DEF", { enumerable: true, get: function () { return defs_1.NG_INJ_DEF; } });
Object.defineProperty(exports, "\u0275NG_PROV_DEF", { enumerable: true, get: function () { return defs_1.NG_PROV_DEF; } });
Object.defineProperty(exports, "\u0275isInjectable", { enumerable: true, get: function () { return defs_1.isInjectable; } });
var create_injector_1 = require("./di/create_injector");
Object.defineProperty(exports, "\u0275createInjector", { enumerable: true, get: function () { return create_injector_1.createInjector; } });
var ng_module_registration_1 = require("./linker/ng_module_registration");
Object.defineProperty(exports, "\u0275\u0275registerNgModuleType", { enumerable: true, get: function () { return ng_module_registration_1.registerNgModuleType; } });
Object.defineProperty(exports, "\u0275setAllowDuplicateNgModuleIdsForTest", { enumerable: true, get: function () { return ng_module_registration_1.setAllowDuplicateNgModuleIdsForTest; } });
var context_discovery_1 = require("./render3/context_discovery");
Object.defineProperty(exports, "\u0275getLContext", { enumerable: true, get: function () { return context_discovery_1.getLContext; } });
var fields_1 = require("./render3/fields");
Object.defineProperty(exports, "\u0275NG_COMP_DEF", { enumerable: true, get: function () { return fields_1.NG_COMP_DEF; } });
Object.defineProperty(exports, "\u0275NG_DIR_DEF", { enumerable: true, get: function () { return fields_1.NG_DIR_DEF; } });
Object.defineProperty(exports, "\u0275NG_ELEMENT_ID", { enumerable: true, get: function () { return fields_1.NG_ELEMENT_ID; } });
Object.defineProperty(exports, "\u0275NG_MOD_DEF", { enumerable: true, get: function () { return fields_1.NG_MOD_DEF; } });
Object.defineProperty(exports, "\u0275NG_PIPE_DEF", { enumerable: true, get: function () { return fields_1.NG_PIPE_DEF; } });
var index_1 = require("./render3/index");
Object.defineProperty(exports, "\u0275Render3ComponentFactory", { enumerable: true, get: function () { return index_1.ComponentFactory; } });
Object.defineProperty(exports, "\u0275Render3ComponentRef", { enumerable: true, get: function () { return index_1.ComponentRef; } });
Object.defineProperty(exports, "\u0275getDirectives", { enumerable: true, get: function () { return index_1.getDirectives; } });
Object.defineProperty(exports, "\u0275getHostElement", { enumerable: true, get: function () { return index_1.getHostElement; } });
Object.defineProperty(exports, "\u0275NgModuleFactory", { enumerable: true, get: function () { return index_1.NgModuleFactory; } });
Object.defineProperty(exports, "\u0275Render3NgModuleRef", { enumerable: true, get: function () { return index_1.NgModuleRef; } });
Object.defineProperty(exports, "\u0275NO_CHANGE", { enumerable: true, get: function () { return index_1.NO_CHANGE; } });
Object.defineProperty(exports, "\u0275setClassMetadata", { enumerable: true, get: function () { return index_1.setClassMetadata; } });
Object.defineProperty(exports, "\u0275setClassMetadataAsync", { enumerable: true, get: function () { return index_1.setClassMetadataAsync; } });
Object.defineProperty(exports, "\u0275setClassDebugInfo", { enumerable: true, get: function () { return index_1.ɵsetClassDebugInfo; } });
Object.defineProperty(exports, "\u0275setLocaleId", { enumerable: true, get: function () { return index_1.setLocaleId; } });
Object.defineProperty(exports, "\u0275store", { enumerable: true, get: function () { return index_1.store; } });
Object.defineProperty(exports, "\u0275DEFER_BLOCK_DEPENDENCY_INTERCEPTOR", { enumerable: true, get: function () { return index_1.ɵDEFER_BLOCK_DEPENDENCY_INTERCEPTOR; } });
Object.defineProperty(exports, "\u0275DEFER_BLOCK_CONFIG", { enumerable: true, get: function () { return index_1.ɵDEFER_BLOCK_CONFIG; } });
Object.defineProperty(exports, "\u0275Framework", { enumerable: true, get: function () { return index_1.Framework; } });
Object.defineProperty(exports, "\u0275AcxChangeDetectionStrategy", { enumerable: true, get: function () { return index_1.AcxChangeDetectionStrategy; } });
Object.defineProperty(exports, "\u0275AcxViewEncapsulation", { enumerable: true, get: function () { return index_1.AcxViewEncapsulation; } });
Object.defineProperty(exports, "\u0275\u0275advance", { enumerable: true, get: function () { return index_1.ɵɵadvance; } });
Object.defineProperty(exports, "\u0275\u0275attribute", { enumerable: true, get: function () { return index_1.ɵɵattribute; } });
Object.defineProperty(exports, "\u0275\u0275attributeInterpolate1", { enumerable: true, get: function () { return index_1.ɵɵattributeInterpolate1; } });
Object.defineProperty(exports, "\u0275\u0275attributeInterpolate2", { enumerable: true, get: function () { return index_1.ɵɵattributeInterpolate2; } });
Object.defineProperty(exports, "\u0275\u0275attributeInterpolate3", { enumerable: true, get: function () { return index_1.ɵɵattributeInterpolate3; } });
Object.defineProperty(exports, "\u0275\u0275attributeInterpolate4", { enumerable: true, get: function () { return index_1.ɵɵattributeInterpolate4; } });
Object.defineProperty(exports, "\u0275\u0275attributeInterpolate5", { enumerable: true, get: function () { return index_1.ɵɵattributeInterpolate5; } });
Object.defineProperty(exports, "\u0275\u0275attributeInterpolate6", { enumerable: true, get: function () { return index_1.ɵɵattributeInterpolate6; } });
Object.defineProperty(exports, "\u0275\u0275attributeInterpolate7", { enumerable: true, get: function () { return index_1.ɵɵattributeInterpolate7; } });
Object.defineProperty(exports, "\u0275\u0275attributeInterpolate8", { enumerable: true, get: function () { return index_1.ɵɵattributeInterpolate8; } });
Object.defineProperty(exports, "\u0275\u0275attributeInterpolateV", { enumerable: true, get: function () { return index_1.ɵɵattributeInterpolateV; } });
Object.defineProperty(exports, "\u0275\u0275classMap", { enumerable: true, get: function () { return index_1.ɵɵclassMap; } });
Object.defineProperty(exports, "\u0275\u0275classMapInterpolate1", { enumerable: true, get: function () { return index_1.ɵɵclassMapInterpolate1; } });
Object.defineProperty(exports, "\u0275\u0275classMapInterpolate2", { enumerable: true, get: function () { return index_1.ɵɵclassMapInterpolate2; } });
Object.defineProperty(exports, "\u0275\u0275classMapInterpolate3", { enumerable: true, get: function () { return index_1.ɵɵclassMapInterpolate3; } });
Object.defineProperty(exports, "\u0275\u0275classMapInterpolate4", { enumerable: true, get: function () { return index_1.ɵɵclassMapInterpolate4; } });
Object.defineProperty(exports, "\u0275\u0275classMapInterpolate5", { enumerable: true, get: function () { return index_1.ɵɵclassMapInterpolate5; } });
Object.defineProperty(exports, "\u0275\u0275classMapInterpolate6", { enumerable: true, get: function () { return index_1.ɵɵclassMapInterpolate6; } });
Object.defineProperty(exports, "\u0275\u0275classMapInterpolate7", { enumerable: true, get: function () { return index_1.ɵɵclassMapInterpolate7; } });
Object.defineProperty(exports, "\u0275\u0275classMapInterpolate8", { enumerable: true, get: function () { return index_1.ɵɵclassMapInterpolate8; } });
Object.defineProperty(exports, "\u0275\u0275classMapInterpolateV", { enumerable: true, get: function () { return index_1.ɵɵclassMapInterpolateV; } });
Object.defineProperty(exports, "\u0275\u0275classProp", { enumerable: true, get: function () { return index_1.ɵɵclassProp; } });
Object.defineProperty(exports, "\u0275\u0275conditional", { enumerable: true, get: function () { return index_1.ɵɵconditional; } });
Object.defineProperty(exports, "\u0275\u0275conditionalCreate", { enumerable: true, get: function () { return index_1.ɵɵconditionalCreate; } });
Object.defineProperty(exports, "\u0275\u0275conditionalBranchCreate", { enumerable: true, get: function () { return index_1.ɵɵconditionalBranchCreate; } });
Object.defineProperty(exports, "\u0275\u0275contentQuery", { enumerable: true, get: function () { return index_1.ɵɵcontentQuery; } });
Object.defineProperty(exports, "\u0275\u0275contentQuerySignal", { enumerable: true, get: function () { return index_1.ɵɵcontentQuerySignal; } });
Object.defineProperty(exports, "\u0275\u0275componentInstance", { enumerable: true, get: function () { return index_1.ɵɵcomponentInstance; } });
Object.defineProperty(exports, "\u0275\u0275CopyDefinitionFeature", { enumerable: true, get: function () { return index_1.ɵɵCopyDefinitionFeature; } });
Object.defineProperty(exports, "\u0275\u0275defineComponent", { enumerable: true, get: function () { return index_1.ɵɵdefineComponent; } });
Object.defineProperty(exports, "\u0275\u0275defineDirective", { enumerable: true, get: function () { return index_1.ɵɵdefineDirective; } });
Object.defineProperty(exports, "\u0275\u0275defineNgModule", { enumerable: true, get: function () { return index_1.ɵɵdefineNgModule; } });
Object.defineProperty(exports, "\u0275\u0275definePipe", { enumerable: true, get: function () { return index_1.ɵɵdefinePipe; } });
Object.defineProperty(exports, "\u0275\u0275directiveInject", { enumerable: true, get: function () { return index_1.ɵɵdirectiveInject; } });
Object.defineProperty(exports, "\u0275\u0275disableBindings", { enumerable: true, get: function () { return index_1.ɵɵdisableBindings; } });
Object.defineProperty(exports, "\u0275\u0275element", { enumerable: true, get: function () { return index_1.ɵɵelement; } });
Object.defineProperty(exports, "\u0275\u0275elementContainer", { enumerable: true, get: function () { return index_1.ɵɵelementContainer; } });
Object.defineProperty(exports, "\u0275\u0275elementContainerEnd", { enumerable: true, get: function () { return index_1.ɵɵelementContainerEnd; } });
Object.defineProperty(exports, "\u0275\u0275elementContainerStart", { enumerable: true, get: function () { return index_1.ɵɵelementContainerStart; } });
Object.defineProperty(exports, "\u0275\u0275elementEnd", { enumerable: true, get: function () { return index_1.ɵɵelementEnd; } });
Object.defineProperty(exports, "\u0275\u0275elementStart", { enumerable: true, get: function () { return index_1.ɵɵelementStart; } });
Object.defineProperty(exports, "\u0275\u0275enableBindings", { enumerable: true, get: function () { return index_1.ɵɵenableBindings; } });
Object.defineProperty(exports, "\u0275\u0275getCurrentView", { enumerable: true, get: function () { return index_1.ɵɵgetCurrentView; } });
Object.defineProperty(exports, "\u0275\u0275getInheritedFactory", { enumerable: true, get: function () { return index_1.ɵɵgetInheritedFactory; } });
Object.defineProperty(exports, "\u0275\u0275domProperty", { enumerable: true, get: function () { return index_1.ɵɵdomProperty; } });
Object.defineProperty(exports, "\u0275\u0275i18n", { enumerable: true, get: function () { return index_1.ɵɵi18n; } });
Object.defineProperty(exports, "\u0275\u0275i18nApply", { enumerable: true, get: function () { return index_1.ɵɵi18nApply; } });
Object.defineProperty(exports, "\u0275\u0275i18nAttributes", { enumerable: true, get: function () { return index_1.ɵɵi18nAttributes; } });
Object.defineProperty(exports, "\u0275\u0275i18nEnd", { enumerable: true, get: function () { return index_1.ɵɵi18nEnd; } });
Object.defineProperty(exports, "\u0275\u0275i18nExp", { enumerable: true, get: function () { return index_1.ɵɵi18nExp; } });
Object.defineProperty(exports, "\u0275\u0275i18nPostprocess", { enumerable: true, get: function () { return index_1.ɵɵi18nPostprocess; } });
Object.defineProperty(exports, "\u0275\u0275i18nStart", { enumerable: true, get: function () { return index_1.ɵɵi18nStart; } });
Object.defineProperty(exports, "\u0275\u0275InheritDefinitionFeature", { enumerable: true, get: function () { return index_1.ɵɵInheritDefinitionFeature; } });
Object.defineProperty(exports, "\u0275\u0275injectAttribute", { enumerable: true, get: function () { return index_1.ɵɵinjectAttribute; } });
Object.defineProperty(exports, "\u0275\u0275invalidFactory", { enumerable: true, get: function () { return index_1.ɵɵinvalidFactory; } });
Object.defineProperty(exports, "\u0275\u0275listener", { enumerable: true, get: function () { return index_1.ɵɵlistener; } });
Object.defineProperty(exports, "\u0275\u0275loadQuery", { enumerable: true, get: function () { return index_1.ɵɵloadQuery; } });
Object.defineProperty(exports, "\u0275\u0275namespaceHTML", { enumerable: true, get: function () { return index_1.ɵɵnamespaceHTML; } });
Object.defineProperty(exports, "\u0275\u0275namespaceMathML", { enumerable: true, get: function () { return index_1.ɵɵnamespaceMathML; } });
Object.defineProperty(exports, "\u0275\u0275namespaceSVG", { enumerable: true, get: function () { return index_1.ɵɵnamespaceSVG; } });
Object.defineProperty(exports, "\u0275\u0275nextContext", { enumerable: true, get: function () { return index_1.ɵɵnextContext; } });
Object.defineProperty(exports, "\u0275\u0275NgOnChangesFeature", { enumerable: true, get: function () { return index_1.ɵɵNgOnChangesFeature; } });
Object.defineProperty(exports, "\u0275\u0275pipe", { enumerable: true, get: function () { return index_1.ɵɵpipe; } });
Object.defineProperty(exports, "\u0275\u0275pipeBind1", { enumerable: true, get: function () { return index_1.ɵɵpipeBind1; } });
Object.defineProperty(exports, "\u0275\u0275pipeBind2", { enumerable: true, get: function () { return index_1.ɵɵpipeBind2; } });
Object.defineProperty(exports, "\u0275\u0275pipeBind3", { enumerable: true, get: function () { return index_1.ɵɵpipeBind3; } });
Object.defineProperty(exports, "\u0275\u0275pipeBind4", { enumerable: true, get: function () { return index_1.ɵɵpipeBind4; } });
Object.defineProperty(exports, "\u0275\u0275pipeBindV", { enumerable: true, get: function () { return index_1.ɵɵpipeBindV; } });
Object.defineProperty(exports, "\u0275\u0275projection", { enumerable: true, get: function () { return index_1.ɵɵprojection; } });
Object.defineProperty(exports, "\u0275\u0275projectionDef", { enumerable: true, get: function () { return index_1.ɵɵprojectionDef; } });
Object.defineProperty(exports, "\u0275\u0275property", { enumerable: true, get: function () { return index_1.ɵɵproperty; } });
Object.defineProperty(exports, "\u0275\u0275propertyInterpolate", { enumerable: true, get: function () { return index_1.ɵɵpropertyInterpolate; } });
Object.defineProperty(exports, "\u0275\u0275propertyInterpolate1", { enumerable: true, get: function () { return index_1.ɵɵpropertyInterpolate1; } });
Object.defineProperty(exports, "\u0275\u0275propertyInterpolate2", { enumerable: true, get: function () { return index_1.ɵɵpropertyInterpolate2; } });
Object.defineProperty(exports, "\u0275\u0275propertyInterpolate3", { enumerable: true, get: function () { return index_1.ɵɵpropertyInterpolate3; } });
Object.defineProperty(exports, "\u0275\u0275propertyInterpolate4", { enumerable: true, get: function () { return index_1.ɵɵpropertyInterpolate4; } });
Object.defineProperty(exports, "\u0275\u0275propertyInterpolate5", { enumerable: true, get: function () { return index_1.ɵɵpropertyInterpolate5; } });
Object.defineProperty(exports, "\u0275\u0275propertyInterpolate6", { enumerable: true, get: function () { return index_1.ɵɵpropertyInterpolate6; } });
Object.defineProperty(exports, "\u0275\u0275propertyInterpolate7", { enumerable: true, get: function () { return index_1.ɵɵpropertyInterpolate7; } });
Object.defineProperty(exports, "\u0275\u0275propertyInterpolate8", { enumerable: true, get: function () { return index_1.ɵɵpropertyInterpolate8; } });
Object.defineProperty(exports, "\u0275\u0275propertyInterpolateV", { enumerable: true, get: function () { return index_1.ɵɵpropertyInterpolateV; } });
Object.defineProperty(exports, "\u0275\u0275ProvidersFeature", { enumerable: true, get: function () { return index_1.ɵɵProvidersFeature; } });
Object.defineProperty(exports, "\u0275\u0275HostDirectivesFeature", { enumerable: true, get: function () { return index_1.ɵɵHostDirectivesFeature; } });
Object.defineProperty(exports, "\u0275\u0275pureFunction0", { enumerable: true, get: function () { return index_1.ɵɵpureFunction0; } });
Object.defineProperty(exports, "\u0275\u0275pureFunction1", { enumerable: true, get: function () { return index_1.ɵɵpureFunction1; } });
Object.defineProperty(exports, "\u0275\u0275pureFunction2", { enumerable: true, get: function () { return index_1.ɵɵpureFunction2; } });
Object.defineProperty(exports, "\u0275\u0275pureFunction3", { enumerable: true, get: function () { return index_1.ɵɵpureFunction3; } });
Object.defineProperty(exports, "\u0275\u0275pureFunction4", { enumerable: true, get: function () { return index_1.ɵɵpureFunction4; } });
Object.defineProperty(exports, "\u0275\u0275pureFunction5", { enumerable: true, get: function () { return index_1.ɵɵpureFunction5; } });
Object.defineProperty(exports, "\u0275\u0275pureFunction6", { enumerable: true, get: function () { return index_1.ɵɵpureFunction6; } });
Object.defineProperty(exports, "\u0275\u0275pureFunction7", { enumerable: true, get: function () { return index_1.ɵɵpureFunction7; } });
Object.defineProperty(exports, "\u0275\u0275pureFunction8", { enumerable: true, get: function () { return index_1.ɵɵpureFunction8; } });
Object.defineProperty(exports, "\u0275\u0275pureFunctionV", { enumerable: true, get: function () { return index_1.ɵɵpureFunctionV; } });
Object.defineProperty(exports, "\u0275\u0275queryAdvance", { enumerable: true, get: function () { return index_1.ɵɵqueryAdvance; } });
Object.defineProperty(exports, "\u0275\u0275queryRefresh", { enumerable: true, get: function () { return index_1.ɵɵqueryRefresh; } });
Object.defineProperty(exports, "\u0275\u0275reference", { enumerable: true, get: function () { return index_1.ɵɵreference; } });
Object.defineProperty(exports, "\u0275\u0275resetView", { enumerable: true, get: function () { return index_1.ɵɵresetView; } });
Object.defineProperty(exports, "\u0275\u0275resolveBody", { enumerable: true, get: function () { return index_1.ɵɵresolveBody; } });
Object.defineProperty(exports, "\u0275\u0275resolveDocument", { enumerable: true, get: function () { return index_1.ɵɵresolveDocument; } });
Object.defineProperty(exports, "\u0275\u0275resolveWindow", { enumerable: true, get: function () { return index_1.ɵɵresolveWindow; } });
Object.defineProperty(exports, "\u0275\u0275restoreView", { enumerable: true, get: function () { return index_1.ɵɵrestoreView; } });
Object.defineProperty(exports, "\u0275\u0275repeater", { enumerable: true, get: function () { return index_1.ɵɵrepeater; } });
Object.defineProperty(exports, "\u0275\u0275repeaterCreate", { enumerable: true, get: function () { return index_1.ɵɵrepeaterCreate; } });
Object.defineProperty(exports, "\u0275\u0275repeaterTrackByIdentity", { enumerable: true, get: function () { return index_1.ɵɵrepeaterTrackByIdentity; } });
Object.defineProperty(exports, "\u0275\u0275repeaterTrackByIndex", { enumerable: true, get: function () { return index_1.ɵɵrepeaterTrackByIndex; } });
Object.defineProperty(exports, "\u0275\u0275setComponentScope", { enumerable: true, get: function () { return index_1.ɵɵsetComponentScope; } });
Object.defineProperty(exports, "\u0275\u0275setNgModuleScope", { enumerable: true, get: function () { return index_1.ɵɵsetNgModuleScope; } });
Object.defineProperty(exports, "\u0275\u0275getComponentDepsFactory", { enumerable: true, get: function () { return index_1.ɵɵgetComponentDepsFactory; } });
Object.defineProperty(exports, "\u0275\u0275ExternalStylesFeature", { enumerable: true, get: function () { return index_1.ɵɵExternalStylesFeature; } });
Object.defineProperty(exports, "\u0275\u0275styleMap", { enumerable: true, get: function () { return index_1.ɵɵstyleMap; } });
Object.defineProperty(exports, "\u0275\u0275styleMapInterpolate1", { enumerable: true, get: function () { return index_1.ɵɵstyleMapInterpolate1; } });
Object.defineProperty(exports, "\u0275\u0275styleMapInterpolate2", { enumerable: true, get: function () { return index_1.ɵɵstyleMapInterpolate2; } });
Object.defineProperty(exports, "\u0275\u0275styleMapInterpolate3", { enumerable: true, get: function () { return index_1.ɵɵstyleMapInterpolate3; } });
Object.defineProperty(exports, "\u0275\u0275styleMapInterpolate4", { enumerable: true, get: function () { return index_1.ɵɵstyleMapInterpolate4; } });
Object.defineProperty(exports, "\u0275\u0275styleMapInterpolate5", { enumerable: true, get: function () { return index_1.ɵɵstyleMapInterpolate5; } });
Object.defineProperty(exports, "\u0275\u0275styleMapInterpolate6", { enumerable: true, get: function () { return index_1.ɵɵstyleMapInterpolate6; } });
Object.defineProperty(exports, "\u0275\u0275styleMapInterpolate7", { enumerable: true, get: function () { return index_1.ɵɵstyleMapInterpolate7; } });
Object.defineProperty(exports, "\u0275\u0275styleMapInterpolate8", { enumerable: true, get: function () { return index_1.ɵɵstyleMapInterpolate8; } });
Object.defineProperty(exports, "\u0275\u0275styleMapInterpolateV", { enumerable: true, get: function () { return index_1.ɵɵstyleMapInterpolateV; } });
Object.defineProperty(exports, "\u0275\u0275styleProp", { enumerable: true, get: function () { return index_1.ɵɵstyleProp; } });
Object.defineProperty(exports, "\u0275\u0275stylePropInterpolate1", { enumerable: true, get: function () { return index_1.ɵɵstylePropInterpolate1; } });
Object.defineProperty(exports, "\u0275\u0275stylePropInterpolate2", { enumerable: true, get: function () { return index_1.ɵɵstylePropInterpolate2; } });
Object.defineProperty(exports, "\u0275\u0275stylePropInterpolate3", { enumerable: true, get: function () { return index_1.ɵɵstylePropInterpolate3; } });
Object.defineProperty(exports, "\u0275\u0275stylePropInterpolate4", { enumerable: true, get: function () { return index_1.ɵɵstylePropInterpolate4; } });
Object.defineProperty(exports, "\u0275\u0275stylePropInterpolate5", { enumerable: true, get: function () { return index_1.ɵɵstylePropInterpolate5; } });
Object.defineProperty(exports, "\u0275\u0275stylePropInterpolate6", { enumerable: true, get: function () { return index_1.ɵɵstylePropInterpolate6; } });
Object.defineProperty(exports, "\u0275\u0275stylePropInterpolate7", { enumerable: true, get: function () { return index_1.ɵɵstylePropInterpolate7; } });
Object.defineProperty(exports, "\u0275\u0275stylePropInterpolate8", { enumerable: true, get: function () { return index_1.ɵɵstylePropInterpolate8; } });
Object.defineProperty(exports, "\u0275\u0275stylePropInterpolateV", { enumerable: true, get: function () { return index_1.ɵɵstylePropInterpolateV; } });
Object.defineProperty(exports, "\u0275\u0275syntheticHostListener", { enumerable: true, get: function () { return index_1.ɵɵsyntheticHostListener; } });
Object.defineProperty(exports, "\u0275\u0275syntheticHostProperty", { enumerable: true, get: function () { return index_1.ɵɵsyntheticHostProperty; } });
Object.defineProperty(exports, "\u0275\u0275template", { enumerable: true, get: function () { return index_1.ɵɵtemplate; } });
Object.defineProperty(exports, "\u0275\u0275templateRefExtractor", { enumerable: true, get: function () { return index_1.ɵɵtemplateRefExtractor; } });
Object.defineProperty(exports, "\u0275\u0275defer", { enumerable: true, get: function () { return index_1.ɵɵdefer; } });
Object.defineProperty(exports, "\u0275\u0275deferWhen", { enumerable: true, get: function () { return index_1.ɵɵdeferWhen; } });
Object.defineProperty(exports, "\u0275\u0275deferOnIdle", { enumerable: true, get: function () { return index_1.ɵɵdeferOnIdle; } });
Object.defineProperty(exports, "\u0275\u0275deferOnImmediate", { enumerable: true, get: function () { return index_1.ɵɵdeferOnImmediate; } });
Object.defineProperty(exports, "\u0275\u0275deferOnTimer", { enumerable: true, get: function () { return index_1.ɵɵdeferOnTimer; } });
Object.defineProperty(exports, "\u0275\u0275deferOnHover", { enumerable: true, get: function () { return index_1.ɵɵdeferOnHover; } });
Object.defineProperty(exports, "\u0275\u0275deferOnInteraction", { enumerable: true, get: function () { return index_1.ɵɵdeferOnInteraction; } });
Object.defineProperty(exports, "\u0275\u0275deferOnViewport", { enumerable: true, get: function () { return index_1.ɵɵdeferOnViewport; } });
Object.defineProperty(exports, "\u0275\u0275deferPrefetchWhen", { enumerable: true, get: function () { return index_1.ɵɵdeferPrefetchWhen; } });
Object.defineProperty(exports, "\u0275\u0275deferPrefetchOnIdle", { enumerable: true, get: function () { return index_1.ɵɵdeferPrefetchOnIdle; } });
Object.defineProperty(exports, "\u0275\u0275deferPrefetchOnImmediate", { enumerable: true, get: function () { return index_1.ɵɵdeferPrefetchOnImmediate; } });
Object.defineProperty(exports, "\u0275\u0275deferPrefetchOnTimer", { enumerable: true, get: function () { return index_1.ɵɵdeferPrefetchOnTimer; } });
Object.defineProperty(exports, "\u0275\u0275deferPrefetchOnHover", { enumerable: true, get: function () { return index_1.ɵɵdeferPrefetchOnHover; } });
Object.defineProperty(exports, "\u0275\u0275deferPrefetchOnInteraction", { enumerable: true, get: function () { return index_1.ɵɵdeferPrefetchOnInteraction; } });
Object.defineProperty(exports, "\u0275\u0275deferPrefetchOnViewport", { enumerable: true, get: function () { return index_1.ɵɵdeferPrefetchOnViewport; } });
Object.defineProperty(exports, "\u0275\u0275deferEnableTimerScheduling", { enumerable: true, get: function () { return index_1.ɵɵdeferEnableTimerScheduling; } });
Object.defineProperty(exports, "\u0275\u0275deferHydrateWhen", { enumerable: true, get: function () { return index_1.ɵɵdeferHydrateWhen; } });
Object.defineProperty(exports, "\u0275\u0275deferHydrateNever", { enumerable: true, get: function () { return index_1.ɵɵdeferHydrateNever; } });
Object.defineProperty(exports, "\u0275\u0275deferHydrateOnIdle", { enumerable: true, get: function () { return index_1.ɵɵdeferHydrateOnIdle; } });
Object.defineProperty(exports, "\u0275\u0275deferHydrateOnImmediate", { enumerable: true, get: function () { return index_1.ɵɵdeferHydrateOnImmediate; } });
Object.defineProperty(exports, "\u0275\u0275deferHydrateOnTimer", { enumerable: true, get: function () { return index_1.ɵɵdeferHydrateOnTimer; } });
Object.defineProperty(exports, "\u0275\u0275deferHydrateOnHover", { enumerable: true, get: function () { return index_1.ɵɵdeferHydrateOnHover; } });
Object.defineProperty(exports, "\u0275\u0275deferHydrateOnInteraction", { enumerable: true, get: function () { return index_1.ɵɵdeferHydrateOnInteraction; } });
Object.defineProperty(exports, "\u0275\u0275deferHydrateOnViewport", { enumerable: true, get: function () { return index_1.ɵɵdeferHydrateOnViewport; } });
Object.defineProperty(exports, "\u0275\u0275text", { enumerable: true, get: function () { return index_1.ɵɵtext; } });
Object.defineProperty(exports, "\u0275\u0275textInterpolate", { enumerable: true, get: function () { return index_1.ɵɵtextInterpolate; } });
Object.defineProperty(exports, "\u0275\u0275textInterpolate1", { enumerable: true, get: function () { return index_1.ɵɵtextInterpolate1; } });
Object.defineProperty(exports, "\u0275\u0275textInterpolate2", { enumerable: true, get: function () { return index_1.ɵɵtextInterpolate2; } });
Object.defineProperty(exports, "\u0275\u0275textInterpolate3", { enumerable: true, get: function () { return index_1.ɵɵtextInterpolate3; } });
Object.defineProperty(exports, "\u0275\u0275textInterpolate4", { enumerable: true, get: function () { return index_1.ɵɵtextInterpolate4; } });
Object.defineProperty(exports, "\u0275\u0275textInterpolate5", { enumerable: true, get: function () { return index_1.ɵɵtextInterpolate5; } });
Object.defineProperty(exports, "\u0275\u0275textInterpolate6", { enumerable: true, get: function () { return index_1.ɵɵtextInterpolate6; } });
Object.defineProperty(exports, "\u0275\u0275textInterpolate7", { enumerable: true, get: function () { return index_1.ɵɵtextInterpolate7; } });
Object.defineProperty(exports, "\u0275\u0275textInterpolate8", { enumerable: true, get: function () { return index_1.ɵɵtextInterpolate8; } });
Object.defineProperty(exports, "\u0275\u0275textInterpolateV", { enumerable: true, get: function () { return index_1.ɵɵtextInterpolateV; } });
Object.defineProperty(exports, "\u0275\u0275viewQuery", { enumerable: true, get: function () { return index_1.ɵɵviewQuery; } });
Object.defineProperty(exports, "\u0275\u0275viewQuerySignal", { enumerable: true, get: function () { return index_1.ɵɵviewQuerySignal; } });
Object.defineProperty(exports, "\u0275\u0275twoWayProperty", { enumerable: true, get: function () { return index_1.ɵɵtwoWayProperty; } });
Object.defineProperty(exports, "\u0275\u0275twoWayBindingSet", { enumerable: true, get: function () { return index_1.ɵɵtwoWayBindingSet; } });
Object.defineProperty(exports, "\u0275\u0275twoWayListener", { enumerable: true, get: function () { return index_1.ɵɵtwoWayListener; } });
Object.defineProperty(exports, "\u0275getUnknownElementStrictMode", { enumerable: true, get: function () { return index_1.ɵgetUnknownElementStrictMode; } });
Object.defineProperty(exports, "\u0275setUnknownElementStrictMode", { enumerable: true, get: function () { return index_1.ɵsetUnknownElementStrictMode; } });
Object.defineProperty(exports, "\u0275getUnknownPropertyStrictMode", { enumerable: true, get: function () { return index_1.ɵgetUnknownPropertyStrictMode; } });
Object.defineProperty(exports, "\u0275setUnknownPropertyStrictMode", { enumerable: true, get: function () { return index_1.ɵsetUnknownPropertyStrictMode; } });
Object.defineProperty(exports, "\u0275\u0275declareLet", { enumerable: true, get: function () { return index_1.ɵɵdeclareLet; } });
Object.defineProperty(exports, "\u0275\u0275storeLet", { enumerable: true, get: function () { return index_1.ɵɵstoreLet; } });
Object.defineProperty(exports, "\u0275\u0275readContextLet", { enumerable: true, get: function () { return index_1.ɵɵreadContextLet; } });
Object.defineProperty(exports, "\u0275\u0275replaceMetadata", { enumerable: true, get: function () { return index_1.ɵɵreplaceMetadata; } });
Object.defineProperty(exports, "\u0275\u0275attachSourceLocations", { enumerable: true, get: function () { return index_1.ɵɵattachSourceLocations; } });
var container_1 = require("./render3/interfaces/container");
Object.defineProperty(exports, "\u0275CONTAINER_HEADER_OFFSET", { enumerable: true, get: function () { return container_1.CONTAINER_HEADER_OFFSET; } });
var context_1 = require("./render3/interfaces/context");
Object.defineProperty(exports, "\u0275LContext", { enumerable: true, get: function () { return context_1.LContext; } });
var document_1 = require("./render3/interfaces/document");
Object.defineProperty(exports, "\u0275setDocument", { enumerable: true, get: function () { return document_1.setDocument; } });
var directive_1 = require("./render3/jit/directive");
Object.defineProperty(exports, "\u0275compileComponent", { enumerable: true, get: function () { return directive_1.compileComponent; } });
Object.defineProperty(exports, "\u0275compileDirective", { enumerable: true, get: function () { return directive_1.compileDirective; } });
var jit_options_1 = require("./render3/jit/jit_options");
Object.defineProperty(exports, "\u0275resetJitOptions", { enumerable: true, get: function () { return jit_options_1.resetJitOptions; } });
var module_1 = require("./render3/jit/module");
Object.defineProperty(exports, "\u0275compileNgModule", { enumerable: true, get: function () { return module_1.compileNgModule; } });
Object.defineProperty(exports, "\u0275compileNgModuleDefs", { enumerable: true, get: function () { return module_1.compileNgModuleDefs; } });
Object.defineProperty(exports, "\u0275flushModuleScopingQueueAsMuchAsPossible", { enumerable: true, get: function () { return module_1.flushModuleScopingQueueAsMuchAsPossible; } });
Object.defineProperty(exports, "\u0275patchComponentDefWithScope", { enumerable: true, get: function () { return module_1.patchComponentDefWithScope; } });
Object.defineProperty(exports, "\u0275resetCompiledComponents", { enumerable: true, get: function () { return module_1.resetCompiledComponents; } });
Object.defineProperty(exports, "\u0275transitiveScopesFor", { enumerable: true, get: function () { return module_1.transitiveScopesFor; } });
var partial_1 = require("./render3/jit/partial");
Object.defineProperty(exports, "\u0275\u0275FactoryTarget", { enumerable: true, get: function () { return partial_1.FactoryTarget; } });
Object.defineProperty(exports, "\u0275\u0275ngDeclareClassMetadata", { enumerable: true, get: function () { return partial_1.ɵɵngDeclareClassMetadata; } });
Object.defineProperty(exports, "\u0275\u0275ngDeclareClassMetadataAsync", { enumerable: true, get: function () { return partial_1.ɵɵngDeclareClassMetadataAsync; } });
Object.defineProperty(exports, "\u0275\u0275ngDeclareComponent", { enumerable: true, get: function () { return partial_1.ɵɵngDeclareComponent; } });
Object.defineProperty(exports, "\u0275\u0275ngDeclareDirective", { enumerable: true, get: function () { return partial_1.ɵɵngDeclareDirective; } });
Object.defineProperty(exports, "\u0275\u0275ngDeclareFactory", { enumerable: true, get: function () { return partial_1.ɵɵngDeclareFactory; } });
Object.defineProperty(exports, "\u0275\u0275ngDeclareInjectable", { enumerable: true, get: function () { return partial_1.ɵɵngDeclareInjectable; } });
Object.defineProperty(exports, "\u0275\u0275ngDeclareInjector", { enumerable: true, get: function () { return partial_1.ɵɵngDeclareInjector; } });
Object.defineProperty(exports, "\u0275\u0275ngDeclareNgModule", { enumerable: true, get: function () { return partial_1.ɵɵngDeclareNgModule; } });
Object.defineProperty(exports, "\u0275\u0275ngDeclarePipe", { enumerable: true, get: function () { return partial_1.ɵɵngDeclarePipe; } });
var pipe_1 = require("./render3/jit/pipe");
Object.defineProperty(exports, "\u0275compilePipe", { enumerable: true, get: function () { return pipe_1.compilePipe; } });
var util_1 = require("./render3/jit/util");
Object.defineProperty(exports, "\u0275isNgModule", { enumerable: true, get: function () { return util_1.isNgModule; } });
var view_ref_1 = require("./render3/view_ref");
Object.defineProperty(exports, "\u0275ViewRef", { enumerable: true, get: function () { return view_ref_1.ViewRef; } });
Object.defineProperty(exports, "\u0275isViewDirty", { enumerable: true, get: function () { return view_ref_1.isViewDirty; } });
Object.defineProperty(exports, "\u0275markForRefresh", { enumerable: true, get: function () { return view_ref_1.markForRefresh; } });
var bypass_1 = require("./sanitization/bypass");
Object.defineProperty(exports, "\u0275bypassSanitizationTrustHtml", { enumerable: true, get: function () { return bypass_1.bypassSanitizationTrustHtml; } });
Object.defineProperty(exports, "\u0275bypassSanitizationTrustResourceUrl", { enumerable: true, get: function () { return bypass_1.bypassSanitizationTrustResourceUrl; } });
Object.defineProperty(exports, "\u0275bypassSanitizationTrustScript", { enumerable: true, get: function () { return bypass_1.bypassSanitizationTrustScript; } });
Object.defineProperty(exports, "\u0275bypassSanitizationTrustStyle", { enumerable: true, get: function () { return bypass_1.bypassSanitizationTrustStyle; } });
Object.defineProperty(exports, "\u0275bypassSanitizationTrustUrl", { enumerable: true, get: function () { return bypass_1.bypassSanitizationTrustUrl; } });
var sanitization_1 = require("./sanitization/sanitization");
Object.defineProperty(exports, "\u0275\u0275sanitizeHtml", { enumerable: true, get: function () { return sanitization_1.ɵɵsanitizeHtml; } });
Object.defineProperty(exports, "\u0275\u0275sanitizeResourceUrl", { enumerable: true, get: function () { return sanitization_1.ɵɵsanitizeResourceUrl; } });
Object.defineProperty(exports, "\u0275\u0275sanitizeScript", { enumerable: true, get: function () { return sanitization_1.ɵɵsanitizeScript; } });
Object.defineProperty(exports, "\u0275\u0275sanitizeStyle", { enumerable: true, get: function () { return sanitization_1.ɵɵsanitizeStyle; } });
Object.defineProperty(exports, "\u0275\u0275sanitizeUrl", { enumerable: true, get: function () { return sanitization_1.ɵɵsanitizeUrl; } });
Object.defineProperty(exports, "\u0275\u0275sanitizeUrlOrResourceUrl", { enumerable: true, get: function () { return sanitization_1.ɵɵsanitizeUrlOrResourceUrl; } });
Object.defineProperty(exports, "\u0275\u0275trustConstantHtml", { enumerable: true, get: function () { return sanitization_1.ɵɵtrustConstantHtml; } });
Object.defineProperty(exports, "\u0275\u0275trustConstantResourceUrl", { enumerable: true, get: function () { return sanitization_1.ɵɵtrustConstantResourceUrl; } });
var iframe_attrs_validation_1 = require("./sanitization/iframe_attrs_validation");
Object.defineProperty(exports, "\u0275\u0275validateIframeAttribute", { enumerable: true, get: function () { return iframe_attrs_validation_1.ɵɵvalidateIframeAttribute; } });
var closure_1 = require("./util/closure");
Object.defineProperty(exports, "\u0275noSideEffects", { enumerable: true, get: function () { return closure_1.noSideEffects; } });
var manager_1 = require("./render3/after_render/manager");
Object.defineProperty(exports, "\u0275AfterRenderManager", { enumerable: true, get: function () { return manager_1.AfterRenderManager; } });
var deps_tracker_1 = require("./render3/deps_tracker/deps_tracker");
Object.defineProperty(exports, "\u0275depsTracker", { enumerable: true, get: function () { return deps_tracker_1.depsTracker; } });
Object.defineProperty(exports, "\u0275USE_RUNTIME_DEPS_TRACKER_FOR_JIT", { enumerable: true, get: function () { return deps_tracker_1.USE_RUNTIME_DEPS_TRACKER_FOR_JIT; } });
var module_2 = require("./render3/jit/module");
Object.defineProperty(exports, "\u0275generateStandaloneInDeclarationsError", { enumerable: true, get: function () { return module_2.generateStandaloneInDeclarationsError; } });
var metadata_1 = require("./render3/metadata");
Object.defineProperty(exports, "\u0275getAsyncClassMetadataFn", { enumerable: true, get: function () { return metadata_1.getAsyncClassMetadataFn; } });
