"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ɵɵpropertyInterpolate = exports.ɵɵproperty = exports.ɵɵprojectionDef = exports.ɵɵprojection = exports.ɵɵnextContext = exports.ɵɵnamespaceSVG = exports.ɵɵnamespaceMathML = exports.ɵɵnamespaceHTML = exports.ɵɵlistener = exports.ɵɵinvalidFactory = exports.ɵɵinjectAttribute = exports.ɵɵdomProperty = exports.ɵɵgetCurrentView = exports.ɵɵelementStart = exports.ɵɵelementEnd = exports.ɵɵelementContainerStart = exports.ɵɵelementContainerEnd = exports.ɵɵelementContainer = exports.ɵɵelement = exports.ɵɵdirectiveInject = exports.ɵɵcomponentInstance = exports.ɵɵclassProp = exports.ɵɵclassMapInterpolateV = exports.ɵɵclassMapInterpolate8 = exports.ɵɵclassMapInterpolate7 = exports.ɵɵclassMapInterpolate6 = exports.ɵɵclassMapInterpolate5 = exports.ɵɵclassMapInterpolate4 = exports.ɵɵclassMapInterpolate3 = exports.ɵɵclassMapInterpolate2 = exports.ɵɵclassMapInterpolate1 = exports.ɵɵclassMap = exports.ɵɵattributeInterpolateV = exports.ɵɵattributeInterpolate8 = exports.ɵɵattributeInterpolate7 = exports.ɵɵattributeInterpolate6 = exports.ɵɵattributeInterpolate5 = exports.ɵɵattributeInterpolate4 = exports.ɵɵattributeInterpolate3 = exports.ɵɵattributeInterpolate2 = exports.ɵɵattributeInterpolate1 = exports.ɵɵattribute = exports.ɵɵadvance = exports.store = exports.setLocaleId = exports.getLocaleId = exports.ɵɵgetInheritedFactory = exports.ComponentRef = exports.ComponentFactoryResolver = exports.ComponentFactory = void 0;
exports.ɵɵdeferOnIdle = exports.ɵɵdeferWhen = exports.ɵɵdefer = exports.ɵɵconditionalBranchCreate = exports.ɵɵconditionalCreate = exports.ɵɵconditional = exports.ɵɵtemplate = exports.ɵɵsyntheticHostProperty = exports.ɵɵsyntheticHostListener = exports.ɵɵstylePropInterpolateV = exports.ɵɵstylePropInterpolate8 = exports.ɵɵstylePropInterpolate7 = exports.ɵɵstylePropInterpolate6 = exports.ɵɵstylePropInterpolate5 = exports.ɵɵstylePropInterpolate4 = exports.ɵɵstylePropInterpolate3 = exports.ɵɵstylePropInterpolate2 = exports.ɵɵstylePropInterpolate1 = exports.ɵɵstyleProp = exports.ɵɵstyleMapInterpolateV = exports.ɵɵstyleMapInterpolate8 = exports.ɵɵstyleMapInterpolate7 = exports.ɵɵstyleMapInterpolate6 = exports.ɵɵstyleMapInterpolate5 = exports.ɵɵstyleMapInterpolate4 = exports.ɵɵstyleMapInterpolate3 = exports.ɵɵstyleMapInterpolate2 = exports.ɵɵstyleMapInterpolate1 = exports.ɵɵstyleMap = exports.ɵɵrepeaterTrackByIndex = exports.ɵɵrepeaterTrackByIdentity = exports.ɵɵrepeaterCreate = exports.ɵɵrepeater = exports.ɵɵreference = exports.ɵɵviewQuerySignal = exports.ɵɵviewQuery = exports.ɵɵqueryAdvance = exports.ɵɵqueryRefresh = exports.ɵɵloadQuery = exports.ɵɵcontentQuerySignal = exports.ɵɵcontentQuery = exports.ɵɵpropertyInterpolateV = exports.ɵɵpropertyInterpolate8 = exports.ɵɵpropertyInterpolate7 = exports.ɵɵpropertyInterpolate6 = exports.ɵɵpropertyInterpolate5 = exports.ɵɵpropertyInterpolate4 = exports.ɵɵpropertyInterpolate3 = exports.ɵɵpropertyInterpolate2 = exports.ɵɵpropertyInterpolate1 = void 0;
exports.ɵɵi18nExp = exports.ɵɵi18nEnd = exports.ɵɵi18nAttributes = exports.ɵɵi18nApply = exports.ɵɵi18n = exports.ɵDEFER_BLOCK_CONFIG = exports.ɵDEFER_BLOCK_DEPENDENCY_INTERCEPTOR = exports.ɵɵdeferEnableTimerScheduling = exports.ɵɵattachSourceLocations = exports.ɵɵreadContextLet = exports.ɵɵstoreLet = exports.ɵɵdeclareLet = exports.ɵsetUnknownPropertyStrictMode = exports.ɵgetUnknownPropertyStrictMode = exports.ɵsetUnknownElementStrictMode = exports.ɵgetUnknownElementStrictMode = exports.ɵɵtwoWayListener = exports.ɵɵtwoWayBindingSet = exports.ɵɵtwoWayProperty = exports.ɵɵtextInterpolateV = exports.ɵɵtextInterpolate8 = exports.ɵɵtextInterpolate7 = exports.ɵɵtextInterpolate6 = exports.ɵɵtextInterpolate5 = exports.ɵɵtextInterpolate4 = exports.ɵɵtextInterpolate3 = exports.ɵɵtextInterpolate2 = exports.ɵɵtextInterpolate1 = exports.ɵɵtextInterpolate = exports.ɵɵtext = exports.ɵɵdeferHydrateOnViewport = exports.ɵɵdeferHydrateOnInteraction = exports.ɵɵdeferHydrateOnHover = exports.ɵɵdeferHydrateOnTimer = exports.ɵɵdeferHydrateOnImmediate = exports.ɵɵdeferHydrateOnIdle = exports.ɵɵdeferHydrateNever = exports.ɵɵdeferHydrateWhen = exports.ɵɵdeferPrefetchOnViewport = exports.ɵɵdeferPrefetchOnInteraction = exports.ɵɵdeferPrefetchOnHover = exports.ɵɵdeferPrefetchOnTimer = exports.ɵɵdeferPrefetchOnImmediate = exports.ɵɵdeferPrefetchOnIdle = exports.ɵɵdeferPrefetchWhen = exports.ɵɵdeferOnViewport = exports.ɵɵdeferOnInteraction = exports.ɵɵdeferOnHover = exports.ɵɵdeferOnTimer = exports.ɵɵdeferOnImmediate = void 0;
exports.ɵɵInheritDefinitionFeature = exports.ɵɵHostDirectivesFeature = exports.ɵɵdefinePipe = exports.ɵɵdefineNgModule = exports.ɵɵdefineDirective = exports.ɵɵdefineComponent = exports.ɵɵCopyDefinitionFeature = exports.getRenderedText = exports.getHostElement = exports.getDirectives = exports.getDirectiveMetadata = exports.getComponent = exports.AcxViewEncapsulation = exports.AcxChangeDetectionStrategy = exports.Framework = exports.ɵɵreplaceMetadata = exports.ɵsetClassDebugInfo = exports.ɵɵgetComponentDepsFactory = exports.ɵɵtemplateRefExtractor = exports.ɵɵresolveWindow = exports.ɵɵresolveDocument = exports.ɵɵresolveBody = exports.NO_CHANGE = exports.ɵɵrestoreView = exports.ɵɵresetView = exports.ɵɵenableBindings = exports.ɵɵdisableBindings = exports.ɵɵpureFunctionV = exports.ɵɵpureFunction8 = exports.ɵɵpureFunction7 = exports.ɵɵpureFunction6 = exports.ɵɵpureFunction5 = exports.ɵɵpureFunction4 = exports.ɵɵpureFunction3 = exports.ɵɵpureFunction2 = exports.ɵɵpureFunction1 = exports.ɵɵpureFunction0 = exports.ɵɵpipeBindV = exports.ɵɵpipeBind4 = exports.ɵɵpipeBind3 = exports.ɵɵpipeBind2 = exports.ɵɵpipeBind1 = exports.ɵɵpipe = exports.createEnvironmentInjector = exports.NgModuleRef = exports.NgModuleFactory = exports.setClassMetadataAsync = exports.setClassMetadata = exports.ɵɵi18nStart = exports.ɵɵi18nPostprocess = void 0;
exports.ɵɵExternalStylesFeature = exports.ɵɵsetNgModuleScope = exports.ɵɵsetComponentScope = exports.ɵɵProvidersFeature = exports.ɵɵNgOnChangesFeature = void 0;
/**
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.dev/license
 */
const definition_1 = require("./definition");
Object.defineProperty(exports, "\u0275\u0275defineComponent", { enumerable: true, get: function () { return definition_1.ɵɵdefineComponent; } });
Object.defineProperty(exports, "\u0275\u0275defineDirective", { enumerable: true, get: function () { return definition_1.ɵɵdefineDirective; } });
Object.defineProperty(exports, "\u0275\u0275defineNgModule", { enumerable: true, get: function () { return definition_1.ɵɵdefineNgModule; } });
Object.defineProperty(exports, "\u0275\u0275definePipe", { enumerable: true, get: function () { return definition_1.ɵɵdefinePipe; } });
const copy_definition_feature_1 = require("./features/copy_definition_feature");
Object.defineProperty(exports, "\u0275\u0275CopyDefinitionFeature", { enumerable: true, get: function () { return copy_definition_feature_1.ɵɵCopyDefinitionFeature; } });
const host_directives_feature_1 = require("./features/host_directives_feature");
Object.defineProperty(exports, "\u0275\u0275HostDirectivesFeature", { enumerable: true, get: function () { return host_directives_feature_1.ɵɵHostDirectivesFeature; } });
const inherit_definition_feature_1 = require("./features/inherit_definition_feature");
Object.defineProperty(exports, "\u0275\u0275InheritDefinitionFeature", { enumerable: true, get: function () { return inherit_definition_feature_1.ɵɵInheritDefinitionFeature; } });
const ng_onchanges_feature_1 = require("./features/ng_onchanges_feature");
Object.defineProperty(exports, "\u0275\u0275NgOnChangesFeature", { enumerable: true, get: function () { return ng_onchanges_feature_1.ɵɵNgOnChangesFeature; } });
const providers_feature_1 = require("./features/providers_feature");
Object.defineProperty(exports, "\u0275\u0275ProvidersFeature", { enumerable: true, get: function () { return providers_feature_1.ɵɵProvidersFeature; } });
const external_styles_feature_1 = require("./features/external_styles_feature");
Object.defineProperty(exports, "\u0275\u0275ExternalStylesFeature", { enumerable: true, get: function () { return external_styles_feature_1.ɵɵExternalStylesFeature; } });
const scope_1 = require("./scope");
Object.defineProperty(exports, "\u0275\u0275setComponentScope", { enumerable: true, get: function () { return scope_1.ɵɵsetComponentScope; } });
Object.defineProperty(exports, "\u0275\u0275setNgModuleScope", { enumerable: true, get: function () { return scope_1.ɵɵsetNgModuleScope; } });
const discovery_utils_1 = require("./util/discovery_utils");
Object.defineProperty(exports, "Framework", { enumerable: true, get: function () { return discovery_utils_1.Framework; } });
Object.defineProperty(exports, "AcxChangeDetectionStrategy", { enumerable: true, get: function () { return discovery_utils_1.AcxChangeDetectionStrategy; } });
Object.defineProperty(exports, "AcxViewEncapsulation", { enumerable: true, get: function () { return discovery_utils_1.AcxViewEncapsulation; } });
Object.defineProperty(exports, "getComponent", { enumerable: true, get: function () { return discovery_utils_1.getComponent; } });
Object.defineProperty(exports, "getDirectiveMetadata", { enumerable: true, get: function () { return discovery_utils_1.getDirectiveMetadata; } });
Object.defineProperty(exports, "getDirectives", { enumerable: true, get: function () { return discovery_utils_1.getDirectives; } });
Object.defineProperty(exports, "getHostElement", { enumerable: true, get: function () { return discovery_utils_1.getHostElement; } });
Object.defineProperty(exports, "getRenderedText", { enumerable: true, get: function () { return discovery_utils_1.getRenderedText; } });
var component_ref_1 = require("./component_ref");
Object.defineProperty(exports, "ComponentFactory", { enumerable: true, get: function () { return component_ref_1.ComponentFactory; } });
Object.defineProperty(exports, "ComponentFactoryResolver", { enumerable: true, get: function () { return component_ref_1.ComponentFactoryResolver; } });
Object.defineProperty(exports, "ComponentRef", { enumerable: true, get: function () { return component_ref_1.ComponentRef; } });
var di_1 = require("./di");
Object.defineProperty(exports, "\u0275\u0275getInheritedFactory", { enumerable: true, get: function () { return di_1.ɵɵgetInheritedFactory; } });
var i18n_locale_id_1 = require("./i18n/i18n_locale_id");
Object.defineProperty(exports, "getLocaleId", { enumerable: true, get: function () { return i18n_locale_id_1.getLocaleId; } });
Object.defineProperty(exports, "setLocaleId", { enumerable: true, get: function () { return i18n_locale_id_1.setLocaleId; } });
var all_1 = require("./instructions/all");
Object.defineProperty(exports, "store", { enumerable: true, get: function () { return all_1.store; } });
Object.defineProperty(exports, "\u0275\u0275advance", { enumerable: true, get: function () { return all_1.ɵɵadvance; } });
Object.defineProperty(exports, "\u0275\u0275attribute", { enumerable: true, get: function () { return all_1.ɵɵattribute; } });
Object.defineProperty(exports, "\u0275\u0275attributeInterpolate1", { enumerable: true, get: function () { return all_1.ɵɵattributeInterpolate1; } });
Object.defineProperty(exports, "\u0275\u0275attributeInterpolate2", { enumerable: true, get: function () { return all_1.ɵɵattributeInterpolate2; } });
Object.defineProperty(exports, "\u0275\u0275attributeInterpolate3", { enumerable: true, get: function () { return all_1.ɵɵattributeInterpolate3; } });
Object.defineProperty(exports, "\u0275\u0275attributeInterpolate4", { enumerable: true, get: function () { return all_1.ɵɵattributeInterpolate4; } });
Object.defineProperty(exports, "\u0275\u0275attributeInterpolate5", { enumerable: true, get: function () { return all_1.ɵɵattributeInterpolate5; } });
Object.defineProperty(exports, "\u0275\u0275attributeInterpolate6", { enumerable: true, get: function () { return all_1.ɵɵattributeInterpolate6; } });
Object.defineProperty(exports, "\u0275\u0275attributeInterpolate7", { enumerable: true, get: function () { return all_1.ɵɵattributeInterpolate7; } });
Object.defineProperty(exports, "\u0275\u0275attributeInterpolate8", { enumerable: true, get: function () { return all_1.ɵɵattributeInterpolate8; } });
Object.defineProperty(exports, "\u0275\u0275attributeInterpolateV", { enumerable: true, get: function () { return all_1.ɵɵattributeInterpolateV; } });
Object.defineProperty(exports, "\u0275\u0275classMap", { enumerable: true, get: function () { return all_1.ɵɵclassMap; } });
Object.defineProperty(exports, "\u0275\u0275classMapInterpolate1", { enumerable: true, get: function () { return all_1.ɵɵclassMapInterpolate1; } });
Object.defineProperty(exports, "\u0275\u0275classMapInterpolate2", { enumerable: true, get: function () { return all_1.ɵɵclassMapInterpolate2; } });
Object.defineProperty(exports, "\u0275\u0275classMapInterpolate3", { enumerable: true, get: function () { return all_1.ɵɵclassMapInterpolate3; } });
Object.defineProperty(exports, "\u0275\u0275classMapInterpolate4", { enumerable: true, get: function () { return all_1.ɵɵclassMapInterpolate4; } });
Object.defineProperty(exports, "\u0275\u0275classMapInterpolate5", { enumerable: true, get: function () { return all_1.ɵɵclassMapInterpolate5; } });
Object.defineProperty(exports, "\u0275\u0275classMapInterpolate6", { enumerable: true, get: function () { return all_1.ɵɵclassMapInterpolate6; } });
Object.defineProperty(exports, "\u0275\u0275classMapInterpolate7", { enumerable: true, get: function () { return all_1.ɵɵclassMapInterpolate7; } });
Object.defineProperty(exports, "\u0275\u0275classMapInterpolate8", { enumerable: true, get: function () { return all_1.ɵɵclassMapInterpolate8; } });
Object.defineProperty(exports, "\u0275\u0275classMapInterpolateV", { enumerable: true, get: function () { return all_1.ɵɵclassMapInterpolateV; } });
Object.defineProperty(exports, "\u0275\u0275classProp", { enumerable: true, get: function () { return all_1.ɵɵclassProp; } });
Object.defineProperty(exports, "\u0275\u0275componentInstance", { enumerable: true, get: function () { return all_1.ɵɵcomponentInstance; } });
Object.defineProperty(exports, "\u0275\u0275directiveInject", { enumerable: true, get: function () { return all_1.ɵɵdirectiveInject; } });
Object.defineProperty(exports, "\u0275\u0275element", { enumerable: true, get: function () { return all_1.ɵɵelement; } });
Object.defineProperty(exports, "\u0275\u0275elementContainer", { enumerable: true, get: function () { return all_1.ɵɵelementContainer; } });
Object.defineProperty(exports, "\u0275\u0275elementContainerEnd", { enumerable: true, get: function () { return all_1.ɵɵelementContainerEnd; } });
Object.defineProperty(exports, "\u0275\u0275elementContainerStart", { enumerable: true, get: function () { return all_1.ɵɵelementContainerStart; } });
Object.defineProperty(exports, "\u0275\u0275elementEnd", { enumerable: true, get: function () { return all_1.ɵɵelementEnd; } });
Object.defineProperty(exports, "\u0275\u0275elementStart", { enumerable: true, get: function () { return all_1.ɵɵelementStart; } });
Object.defineProperty(exports, "\u0275\u0275getCurrentView", { enumerable: true, get: function () { return all_1.ɵɵgetCurrentView; } });
Object.defineProperty(exports, "\u0275\u0275domProperty", { enumerable: true, get: function () { return all_1.ɵɵdomProperty; } });
Object.defineProperty(exports, "\u0275\u0275injectAttribute", { enumerable: true, get: function () { return all_1.ɵɵinjectAttribute; } });
Object.defineProperty(exports, "\u0275\u0275invalidFactory", { enumerable: true, get: function () { return all_1.ɵɵinvalidFactory; } });
Object.defineProperty(exports, "\u0275\u0275listener", { enumerable: true, get: function () { return all_1.ɵɵlistener; } });
Object.defineProperty(exports, "\u0275\u0275namespaceHTML", { enumerable: true, get: function () { return all_1.ɵɵnamespaceHTML; } });
Object.defineProperty(exports, "\u0275\u0275namespaceMathML", { enumerable: true, get: function () { return all_1.ɵɵnamespaceMathML; } });
Object.defineProperty(exports, "\u0275\u0275namespaceSVG", { enumerable: true, get: function () { return all_1.ɵɵnamespaceSVG; } });
Object.defineProperty(exports, "\u0275\u0275nextContext", { enumerable: true, get: function () { return all_1.ɵɵnextContext; } });
Object.defineProperty(exports, "\u0275\u0275projection", { enumerable: true, get: function () { return all_1.ɵɵprojection; } });
Object.defineProperty(exports, "\u0275\u0275projectionDef", { enumerable: true, get: function () { return all_1.ɵɵprojectionDef; } });
Object.defineProperty(exports, "\u0275\u0275property", { enumerable: true, get: function () { return all_1.ɵɵproperty; } });
Object.defineProperty(exports, "\u0275\u0275propertyInterpolate", { enumerable: true, get: function () { return all_1.ɵɵpropertyInterpolate; } });
Object.defineProperty(exports, "\u0275\u0275propertyInterpolate1", { enumerable: true, get: function () { return all_1.ɵɵpropertyInterpolate1; } });
Object.defineProperty(exports, "\u0275\u0275propertyInterpolate2", { enumerable: true, get: function () { return all_1.ɵɵpropertyInterpolate2; } });
Object.defineProperty(exports, "\u0275\u0275propertyInterpolate3", { enumerable: true, get: function () { return all_1.ɵɵpropertyInterpolate3; } });
Object.defineProperty(exports, "\u0275\u0275propertyInterpolate4", { enumerable: true, get: function () { return all_1.ɵɵpropertyInterpolate4; } });
Object.defineProperty(exports, "\u0275\u0275propertyInterpolate5", { enumerable: true, get: function () { return all_1.ɵɵpropertyInterpolate5; } });
Object.defineProperty(exports, "\u0275\u0275propertyInterpolate6", { enumerable: true, get: function () { return all_1.ɵɵpropertyInterpolate6; } });
Object.defineProperty(exports, "\u0275\u0275propertyInterpolate7", { enumerable: true, get: function () { return all_1.ɵɵpropertyInterpolate7; } });
Object.defineProperty(exports, "\u0275\u0275propertyInterpolate8", { enumerable: true, get: function () { return all_1.ɵɵpropertyInterpolate8; } });
Object.defineProperty(exports, "\u0275\u0275propertyInterpolateV", { enumerable: true, get: function () { return all_1.ɵɵpropertyInterpolateV; } });
Object.defineProperty(exports, "\u0275\u0275contentQuery", { enumerable: true, get: function () { return all_1.ɵɵcontentQuery; } });
Object.defineProperty(exports, "\u0275\u0275contentQuerySignal", { enumerable: true, get: function () { return all_1.ɵɵcontentQuerySignal; } });
Object.defineProperty(exports, "\u0275\u0275loadQuery", { enumerable: true, get: function () { return all_1.ɵɵloadQuery; } });
Object.defineProperty(exports, "\u0275\u0275queryRefresh", { enumerable: true, get: function () { return all_1.ɵɵqueryRefresh; } });
Object.defineProperty(exports, "\u0275\u0275queryAdvance", { enumerable: true, get: function () { return all_1.ɵɵqueryAdvance; } });
Object.defineProperty(exports, "\u0275\u0275viewQuery", { enumerable: true, get: function () { return all_1.ɵɵviewQuery; } });
Object.defineProperty(exports, "\u0275\u0275viewQuerySignal", { enumerable: true, get: function () { return all_1.ɵɵviewQuerySignal; } });
Object.defineProperty(exports, "\u0275\u0275reference", { enumerable: true, get: function () { return all_1.ɵɵreference; } });
Object.defineProperty(exports, "\u0275\u0275repeater", { enumerable: true, get: function () { return all_1.ɵɵrepeater; } });
Object.defineProperty(exports, "\u0275\u0275repeaterCreate", { enumerable: true, get: function () { return all_1.ɵɵrepeaterCreate; } });
Object.defineProperty(exports, "\u0275\u0275repeaterTrackByIdentity", { enumerable: true, get: function () { return all_1.ɵɵrepeaterTrackByIdentity; } });
Object.defineProperty(exports, "\u0275\u0275repeaterTrackByIndex", { enumerable: true, get: function () { return all_1.ɵɵrepeaterTrackByIndex; } });
Object.defineProperty(exports, "\u0275\u0275styleMap", { enumerable: true, get: function () { return all_1.ɵɵstyleMap; } });
Object.defineProperty(exports, "\u0275\u0275styleMapInterpolate1", { enumerable: true, get: function () { return all_1.ɵɵstyleMapInterpolate1; } });
Object.defineProperty(exports, "\u0275\u0275styleMapInterpolate2", { enumerable: true, get: function () { return all_1.ɵɵstyleMapInterpolate2; } });
Object.defineProperty(exports, "\u0275\u0275styleMapInterpolate3", { enumerable: true, get: function () { return all_1.ɵɵstyleMapInterpolate3; } });
Object.defineProperty(exports, "\u0275\u0275styleMapInterpolate4", { enumerable: true, get: function () { return all_1.ɵɵstyleMapInterpolate4; } });
Object.defineProperty(exports, "\u0275\u0275styleMapInterpolate5", { enumerable: true, get: function () { return all_1.ɵɵstyleMapInterpolate5; } });
Object.defineProperty(exports, "\u0275\u0275styleMapInterpolate6", { enumerable: true, get: function () { return all_1.ɵɵstyleMapInterpolate6; } });
Object.defineProperty(exports, "\u0275\u0275styleMapInterpolate7", { enumerable: true, get: function () { return all_1.ɵɵstyleMapInterpolate7; } });
Object.defineProperty(exports, "\u0275\u0275styleMapInterpolate8", { enumerable: true, get: function () { return all_1.ɵɵstyleMapInterpolate8; } });
Object.defineProperty(exports, "\u0275\u0275styleMapInterpolateV", { enumerable: true, get: function () { return all_1.ɵɵstyleMapInterpolateV; } });
Object.defineProperty(exports, "\u0275\u0275styleProp", { enumerable: true, get: function () { return all_1.ɵɵstyleProp; } });
Object.defineProperty(exports, "\u0275\u0275stylePropInterpolate1", { enumerable: true, get: function () { return all_1.ɵɵstylePropInterpolate1; } });
Object.defineProperty(exports, "\u0275\u0275stylePropInterpolate2", { enumerable: true, get: function () { return all_1.ɵɵstylePropInterpolate2; } });
Object.defineProperty(exports, "\u0275\u0275stylePropInterpolate3", { enumerable: true, get: function () { return all_1.ɵɵstylePropInterpolate3; } });
Object.defineProperty(exports, "\u0275\u0275stylePropInterpolate4", { enumerable: true, get: function () { return all_1.ɵɵstylePropInterpolate4; } });
Object.defineProperty(exports, "\u0275\u0275stylePropInterpolate5", { enumerable: true, get: function () { return all_1.ɵɵstylePropInterpolate5; } });
Object.defineProperty(exports, "\u0275\u0275stylePropInterpolate6", { enumerable: true, get: function () { return all_1.ɵɵstylePropInterpolate6; } });
Object.defineProperty(exports, "\u0275\u0275stylePropInterpolate7", { enumerable: true, get: function () { return all_1.ɵɵstylePropInterpolate7; } });
Object.defineProperty(exports, "\u0275\u0275stylePropInterpolate8", { enumerable: true, get: function () { return all_1.ɵɵstylePropInterpolate8; } });
Object.defineProperty(exports, "\u0275\u0275stylePropInterpolateV", { enumerable: true, get: function () { return all_1.ɵɵstylePropInterpolateV; } });
Object.defineProperty(exports, "\u0275\u0275syntheticHostListener", { enumerable: true, get: function () { return all_1.ɵɵsyntheticHostListener; } });
Object.defineProperty(exports, "\u0275\u0275syntheticHostProperty", { enumerable: true, get: function () { return all_1.ɵɵsyntheticHostProperty; } });
Object.defineProperty(exports, "\u0275\u0275template", { enumerable: true, get: function () { return all_1.ɵɵtemplate; } });
Object.defineProperty(exports, "\u0275\u0275conditional", { enumerable: true, get: function () { return all_1.ɵɵconditional; } });
Object.defineProperty(exports, "\u0275\u0275conditionalCreate", { enumerable: true, get: function () { return all_1.ɵɵconditionalCreate; } });
Object.defineProperty(exports, "\u0275\u0275conditionalBranchCreate", { enumerable: true, get: function () { return all_1.ɵɵconditionalBranchCreate; } });
Object.defineProperty(exports, "\u0275\u0275defer", { enumerable: true, get: function () { return all_1.ɵɵdefer; } });
Object.defineProperty(exports, "\u0275\u0275deferWhen", { enumerable: true, get: function () { return all_1.ɵɵdeferWhen; } });
Object.defineProperty(exports, "\u0275\u0275deferOnIdle", { enumerable: true, get: function () { return all_1.ɵɵdeferOnIdle; } });
Object.defineProperty(exports, "\u0275\u0275deferOnImmediate", { enumerable: true, get: function () { return all_1.ɵɵdeferOnImmediate; } });
Object.defineProperty(exports, "\u0275\u0275deferOnTimer", { enumerable: true, get: function () { return all_1.ɵɵdeferOnTimer; } });
Object.defineProperty(exports, "\u0275\u0275deferOnHover", { enumerable: true, get: function () { return all_1.ɵɵdeferOnHover; } });
Object.defineProperty(exports, "\u0275\u0275deferOnInteraction", { enumerable: true, get: function () { return all_1.ɵɵdeferOnInteraction; } });
Object.defineProperty(exports, "\u0275\u0275deferOnViewport", { enumerable: true, get: function () { return all_1.ɵɵdeferOnViewport; } });
Object.defineProperty(exports, "\u0275\u0275deferPrefetchWhen", { enumerable: true, get: function () { return all_1.ɵɵdeferPrefetchWhen; } });
Object.defineProperty(exports, "\u0275\u0275deferPrefetchOnIdle", { enumerable: true, get: function () { return all_1.ɵɵdeferPrefetchOnIdle; } });
Object.defineProperty(exports, "\u0275\u0275deferPrefetchOnImmediate", { enumerable: true, get: function () { return all_1.ɵɵdeferPrefetchOnImmediate; } });
Object.defineProperty(exports, "\u0275\u0275deferPrefetchOnTimer", { enumerable: true, get: function () { return all_1.ɵɵdeferPrefetchOnTimer; } });
Object.defineProperty(exports, "\u0275\u0275deferPrefetchOnHover", { enumerable: true, get: function () { return all_1.ɵɵdeferPrefetchOnHover; } });
Object.defineProperty(exports, "\u0275\u0275deferPrefetchOnInteraction", { enumerable: true, get: function () { return all_1.ɵɵdeferPrefetchOnInteraction; } });
Object.defineProperty(exports, "\u0275\u0275deferPrefetchOnViewport", { enumerable: true, get: function () { return all_1.ɵɵdeferPrefetchOnViewport; } });
Object.defineProperty(exports, "\u0275\u0275deferHydrateWhen", { enumerable: true, get: function () { return all_1.ɵɵdeferHydrateWhen; } });
Object.defineProperty(exports, "\u0275\u0275deferHydrateNever", { enumerable: true, get: function () { return all_1.ɵɵdeferHydrateNever; } });
Object.defineProperty(exports, "\u0275\u0275deferHydrateOnIdle", { enumerable: true, get: function () { return all_1.ɵɵdeferHydrateOnIdle; } });
Object.defineProperty(exports, "\u0275\u0275deferHydrateOnImmediate", { enumerable: true, get: function () { return all_1.ɵɵdeferHydrateOnImmediate; } });
Object.defineProperty(exports, "\u0275\u0275deferHydrateOnTimer", { enumerable: true, get: function () { return all_1.ɵɵdeferHydrateOnTimer; } });
Object.defineProperty(exports, "\u0275\u0275deferHydrateOnHover", { enumerable: true, get: function () { return all_1.ɵɵdeferHydrateOnHover; } });
Object.defineProperty(exports, "\u0275\u0275deferHydrateOnInteraction", { enumerable: true, get: function () { return all_1.ɵɵdeferHydrateOnInteraction; } });
Object.defineProperty(exports, "\u0275\u0275deferHydrateOnViewport", { enumerable: true, get: function () { return all_1.ɵɵdeferHydrateOnViewport; } });
Object.defineProperty(exports, "\u0275\u0275text", { enumerable: true, get: function () { return all_1.ɵɵtext; } });
Object.defineProperty(exports, "\u0275\u0275textInterpolate", { enumerable: true, get: function () { return all_1.ɵɵtextInterpolate; } });
Object.defineProperty(exports, "\u0275\u0275textInterpolate1", { enumerable: true, get: function () { return all_1.ɵɵtextInterpolate1; } });
Object.defineProperty(exports, "\u0275\u0275textInterpolate2", { enumerable: true, get: function () { return all_1.ɵɵtextInterpolate2; } });
Object.defineProperty(exports, "\u0275\u0275textInterpolate3", { enumerable: true, get: function () { return all_1.ɵɵtextInterpolate3; } });
Object.defineProperty(exports, "\u0275\u0275textInterpolate4", { enumerable: true, get: function () { return all_1.ɵɵtextInterpolate4; } });
Object.defineProperty(exports, "\u0275\u0275textInterpolate5", { enumerable: true, get: function () { return all_1.ɵɵtextInterpolate5; } });
Object.defineProperty(exports, "\u0275\u0275textInterpolate6", { enumerable: true, get: function () { return all_1.ɵɵtextInterpolate6; } });
Object.defineProperty(exports, "\u0275\u0275textInterpolate7", { enumerable: true, get: function () { return all_1.ɵɵtextInterpolate7; } });
Object.defineProperty(exports, "\u0275\u0275textInterpolate8", { enumerable: true, get: function () { return all_1.ɵɵtextInterpolate8; } });
Object.defineProperty(exports, "\u0275\u0275textInterpolateV", { enumerable: true, get: function () { return all_1.ɵɵtextInterpolateV; } });
Object.defineProperty(exports, "\u0275\u0275twoWayProperty", { enumerable: true, get: function () { return all_1.ɵɵtwoWayProperty; } });
Object.defineProperty(exports, "\u0275\u0275twoWayBindingSet", { enumerable: true, get: function () { return all_1.ɵɵtwoWayBindingSet; } });
Object.defineProperty(exports, "\u0275\u0275twoWayListener", { enumerable: true, get: function () { return all_1.ɵɵtwoWayListener; } });
Object.defineProperty(exports, "\u0275getUnknownElementStrictMode", { enumerable: true, get: function () { return all_1.ɵgetUnknownElementStrictMode; } });
Object.defineProperty(exports, "\u0275setUnknownElementStrictMode", { enumerable: true, get: function () { return all_1.ɵsetUnknownElementStrictMode; } });
Object.defineProperty(exports, "\u0275getUnknownPropertyStrictMode", { enumerable: true, get: function () { return all_1.ɵgetUnknownPropertyStrictMode; } });
Object.defineProperty(exports, "\u0275setUnknownPropertyStrictMode", { enumerable: true, get: function () { return all_1.ɵsetUnknownPropertyStrictMode; } });
Object.defineProperty(exports, "\u0275\u0275declareLet", { enumerable: true, get: function () { return all_1.ɵɵdeclareLet; } });
Object.defineProperty(exports, "\u0275\u0275storeLet", { enumerable: true, get: function () { return all_1.ɵɵstoreLet; } });
Object.defineProperty(exports, "\u0275\u0275readContextLet", { enumerable: true, get: function () { return all_1.ɵɵreadContextLet; } });
Object.defineProperty(exports, "\u0275\u0275attachSourceLocations", { enumerable: true, get: function () { return all_1.ɵɵattachSourceLocations; } });
var rendering_1 = require("../defer/rendering");
Object.defineProperty(exports, "\u0275\u0275deferEnableTimerScheduling", { enumerable: true, get: function () { return rendering_1.ɵɵdeferEnableTimerScheduling; } });
Object.defineProperty(exports, "\u0275DEFER_BLOCK_DEPENDENCY_INTERCEPTOR", { enumerable: true, get: function () { return rendering_1.DEFER_BLOCK_DEPENDENCY_INTERCEPTOR; } });
Object.defineProperty(exports, "\u0275DEFER_BLOCK_CONFIG", { enumerable: true, get: function () { return rendering_1.DEFER_BLOCK_CONFIG; } });
var i18n_1 = require("./instructions/i18n");
Object.defineProperty(exports, "\u0275\u0275i18n", { enumerable: true, get: function () { return i18n_1.ɵɵi18n; } });
Object.defineProperty(exports, "\u0275\u0275i18nApply", { enumerable: true, get: function () { return i18n_1.ɵɵi18nApply; } });
Object.defineProperty(exports, "\u0275\u0275i18nAttributes", { enumerable: true, get: function () { return i18n_1.ɵɵi18nAttributes; } });
Object.defineProperty(exports, "\u0275\u0275i18nEnd", { enumerable: true, get: function () { return i18n_1.ɵɵi18nEnd; } });
Object.defineProperty(exports, "\u0275\u0275i18nExp", { enumerable: true, get: function () { return i18n_1.ɵɵi18nExp; } });
Object.defineProperty(exports, "\u0275\u0275i18nPostprocess", { enumerable: true, get: function () { return i18n_1.ɵɵi18nPostprocess; } });
Object.defineProperty(exports, "\u0275\u0275i18nStart", { enumerable: true, get: function () { return i18n_1.ɵɵi18nStart; } });
var metadata_1 = require("./metadata");
Object.defineProperty(exports, "setClassMetadata", { enumerable: true, get: function () { return metadata_1.setClassMetadata; } });
Object.defineProperty(exports, "setClassMetadataAsync", { enumerable: true, get: function () { return metadata_1.setClassMetadataAsync; } });
var ng_module_ref_1 = require("./ng_module_ref");
Object.defineProperty(exports, "NgModuleFactory", { enumerable: true, get: function () { return ng_module_ref_1.NgModuleFactory; } });
Object.defineProperty(exports, "NgModuleRef", { enumerable: true, get: function () { return ng_module_ref_1.NgModuleRef; } });
Object.defineProperty(exports, "createEnvironmentInjector", { enumerable: true, get: function () { return ng_module_ref_1.createEnvironmentInjector; } });
var pipe_1 = require("./pipe");
Object.defineProperty(exports, "\u0275\u0275pipe", { enumerable: true, get: function () { return pipe_1.ɵɵpipe; } });
Object.defineProperty(exports, "\u0275\u0275pipeBind1", { enumerable: true, get: function () { return pipe_1.ɵɵpipeBind1; } });
Object.defineProperty(exports, "\u0275\u0275pipeBind2", { enumerable: true, get: function () { return pipe_1.ɵɵpipeBind2; } });
Object.defineProperty(exports, "\u0275\u0275pipeBind3", { enumerable: true, get: function () { return pipe_1.ɵɵpipeBind3; } });
Object.defineProperty(exports, "\u0275\u0275pipeBind4", { enumerable: true, get: function () { return pipe_1.ɵɵpipeBind4; } });
Object.defineProperty(exports, "\u0275\u0275pipeBindV", { enumerable: true, get: function () { return pipe_1.ɵɵpipeBindV; } });
var pure_function_1 = require("./pure_function");
Object.defineProperty(exports, "\u0275\u0275pureFunction0", { enumerable: true, get: function () { return pure_function_1.ɵɵpureFunction0; } });
Object.defineProperty(exports, "\u0275\u0275pureFunction1", { enumerable: true, get: function () { return pure_function_1.ɵɵpureFunction1; } });
Object.defineProperty(exports, "\u0275\u0275pureFunction2", { enumerable: true, get: function () { return pure_function_1.ɵɵpureFunction2; } });
Object.defineProperty(exports, "\u0275\u0275pureFunction3", { enumerable: true, get: function () { return pure_function_1.ɵɵpureFunction3; } });
Object.defineProperty(exports, "\u0275\u0275pureFunction4", { enumerable: true, get: function () { return pure_function_1.ɵɵpureFunction4; } });
Object.defineProperty(exports, "\u0275\u0275pureFunction5", { enumerable: true, get: function () { return pure_function_1.ɵɵpureFunction5; } });
Object.defineProperty(exports, "\u0275\u0275pureFunction6", { enumerable: true, get: function () { return pure_function_1.ɵɵpureFunction6; } });
Object.defineProperty(exports, "\u0275\u0275pureFunction7", { enumerable: true, get: function () { return pure_function_1.ɵɵpureFunction7; } });
Object.defineProperty(exports, "\u0275\u0275pureFunction8", { enumerable: true, get: function () { return pure_function_1.ɵɵpureFunction8; } });
Object.defineProperty(exports, "\u0275\u0275pureFunctionV", { enumerable: true, get: function () { return pure_function_1.ɵɵpureFunctionV; } });
var state_1 = require("./state");
Object.defineProperty(exports, "\u0275\u0275disableBindings", { enumerable: true, get: function () { return state_1.ɵɵdisableBindings; } });
Object.defineProperty(exports, "\u0275\u0275enableBindings", { enumerable: true, get: function () { return state_1.ɵɵenableBindings; } });
Object.defineProperty(exports, "\u0275\u0275resetView", { enumerable: true, get: function () { return state_1.ɵɵresetView; } });
Object.defineProperty(exports, "\u0275\u0275restoreView", { enumerable: true, get: function () { return state_1.ɵɵrestoreView; } });
var tokens_1 = require("./tokens");
Object.defineProperty(exports, "NO_CHANGE", { enumerable: true, get: function () { return tokens_1.NO_CHANGE; } });
var misc_utils_1 = require("./util/misc_utils");
Object.defineProperty(exports, "\u0275\u0275resolveBody", { enumerable: true, get: function () { return misc_utils_1.ɵɵresolveBody; } });
Object.defineProperty(exports, "\u0275\u0275resolveDocument", { enumerable: true, get: function () { return misc_utils_1.ɵɵresolveDocument; } });
Object.defineProperty(exports, "\u0275\u0275resolveWindow", { enumerable: true, get: function () { return misc_utils_1.ɵɵresolveWindow; } });
var view_engine_compatibility_prebound_1 = require("./view_engine_compatibility_prebound");
Object.defineProperty(exports, "\u0275\u0275templateRefExtractor", { enumerable: true, get: function () { return view_engine_compatibility_prebound_1.ɵɵtemplateRefExtractor; } });
var local_compilation_1 = require("./local_compilation");
Object.defineProperty(exports, "\u0275\u0275getComponentDepsFactory", { enumerable: true, get: function () { return local_compilation_1.ɵɵgetComponentDepsFactory; } });
var set_debug_info_1 = require("./debug/set_debug_info");
Object.defineProperty(exports, "\u0275setClassDebugInfo", { enumerable: true, get: function () { return set_debug_info_1.ɵsetClassDebugInfo; } });
var hmr_1 = require("./hmr");
Object.defineProperty(exports, "\u0275\u0275replaceMetadata", { enumerable: true, get: function () { return hmr_1.ɵɵreplaceMetadata; } });
